// Emacs style mode select   -*- C++ -*- 
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// $Log:$
//
// DESCRIPTION:
//	Moving object handling. Spawn functions.
//
//-----------------------------------------------------------------------------

static const char
rcsid[] = "$Id: p_mobj.c,v 1.5 1997/02/03 22:45:12 b1 Exp $";

#include "i_system.h"
#include "z_zone.h"
#include "m_random.h"

#include "doomdef.h"
#include "p_local.h"
#include "sounds.h"

#include "st_stuff.h"
#include "hu_stuff.h"

#include "s_sound.h"

#include "doomstat.h"

#define _finesine(a) finesine[a]
#define _finecosine(a) finecosine[a]

void WriteDebug(char *);
char MsgText[256];

void G_PlayerReborn (int player);
void P_SpawnMapThing (mapthing_t*	mthing);


//
// P_SetMobjState
// Returns true if the mobj is still present.
//
int test;


/* //debugging...
struct { const char* pszName; const char* pszSprite; const char* pszFuncName; const char* pszNextState; } thestatenames[] = {
    {"S_NULL","SPR_TROO","NULL","S_NULL"},	// "S_NULL",
    {"S_LIGHTDONE","SPR_SHTG","A_Light0","S_NULL"},	// S_LIGHTDONE
    {"S_PUNCH","SPR_PUNG","A_WeaponReady","S_PUNCH"},	// S_PUNCH
    {"S_PUNCHDOWN","SPR_PUNG","A_Lower","S_PUNCHDOWN"},	// S_PUNCHDOWN
    {"S_PUNCHUP","SPR_PUNG","A_Raise","S_PUNCHUP"},	// S_PUNCHUP
    {"S_PUNCH1","SPR_PUNG","NULL","S_PUNCH2"},		// S_PUNCH1
    {"S_PUNCH2","SPR_PUNG","A_Punch","S_PUNCH3"},	// S_PUNCH2
    {"S_PUNCH3","SPR_PUNG","NULL","S_PUNCH4"},		// S_PUNCH3
    {"S_PUNCH4","SPR_PUNG","NULL","S_PUNCH5"},		// S_PUNCH4
    {"S_PUNCH5","SPR_PUNG","A_ReFire","S_PUNCH"},	// S_PUNCH5
    {"S_PISTOL","SPR_PISG","A_WeaponReady","S_PISTOL"},// S_PISTOL
    {"S_PISTOLDOWN","SPR_PISG","A_Lower","S_PISTOLDOWN"},	// S_PISTOLDOWN
    {"S_PISTOLUP","SPR_PISG","A_Raise","S_PISTOLUP"},	// S_PISTOLUP
    {"S_PISTOL1","SPR_PISG","NULL","S_PISTOL2"},	// S_PISTOL1
    {"S_PISTOL2","SPR_PISG","A_FirePistol","S_PISTOL3"},// S_PISTOL2
    {"S_PISTOL3","SPR_PISG","NULL","S_PISTOL4"},	// S_PISTOL3
    {"S_PISTOL4","SPR_PISG","A_ReFire","S_PISTOL"},	// S_PISTOL4
    {"S_PISTOLFLASH","SPR_PISF","A_Light1","S_LIGHTDONE"},	// S_PISTOLFLASH
    {"S_SGUN","SPR_SHTG","A_WeaponReady","S_SGUN"},	// S_SGUN
    {"S_SGUNDOWN","SPR_SHTG","A_Lower","S_SGUNDOWN"},	// S_SGUNDOWN
    {"S_SGUNUP","SPR_SHTG","A_Raise","S_SGUNUP"},	// S_SGUNUP
    {"S_SGUN1","SPR_SHTG","NULL","S_SGUN2"},	// S_SGUN1
    {"S_SGUN2","SPR_SHTG","A_FireShotgun","S_SGUN3"},	// S_SGUN2
    {"S_SGUN3","SPR_SHTG","NULL","S_SGUN4"},	// S_SGUN3
    {"S_SGUN4","SPR_SHTG","NULL","S_SGUN5"},	// S_SGUN4
    {"S_SGUN5","SPR_SHTG","NULL","S_SGUN6"},	// S_SGUN5
    {"S_SGUN6","SPR_SHTG","NULL","S_SGUN7"},	// S_SGUN6
    {"S_SGUN7","SPR_SHTG","NULL","S_SGUN8"},	// S_SGUN7
    {"S_SGUN8","SPR_SHTG","NULL","S_SGUN9"},	// S_SGUN8
    {"S_SGUN9","SPR_SHTG","A_ReFire","S_SGUN"},	// S_SGUN9
    {"S_SGUNFLASH1","SPR_SHTF","A_Light1","S_SGUNFLASH2"},	// S_SGUNFLASH1
    {"S_SGUNFLASH2","SPR_SHTF","A_Light2","S_LIGHTDONE"},	// S_SGUNFLASH2
    {"S_DSGUN","SPR_SHT2","A_WeaponReady","S_DSGUN"},	// S_DSGUN
    {"S_DSGUNDOWN","SPR_SHT2","A_Lower","S_DSGUNDOWN"},	// S_DSGUNDOWN
    {"S_DSGUNUP","SPR_SHT2","A_Raise","S_DSGUNUP"},	// S_DSGUNUP
    {"S_DSGUN1","SPR_SHT2","NULL","S_DSGUN2"},	// S_DSGUN1
    {"S_DSGUN2","SPR_SHT2","A_FireShotgun2","S_DSGUN3"},	// S_DSGUN2
    {"S_DSGUN3","SPR_SHT2","NULL","S_DSGUN4"},	// S_DSGUN3
    {"S_DSGUN4","SPR_SHT2","A_CheckReload","S_DSGUN5"},	// S_DSGUN4
    {"S_DSGUN5","SPR_SHT2","A_OpenShotgun2","S_DSGUN6"},	// S_DSGUN5
    {"S_DSGUN6","SPR_SHT2","NULL","S_DSGUN7"},	// S_DSGUN6
    {"S_DSGUN7","SPR_SHT2","A_LoadShotgun2","S_DSGUN8"},	// S_DSGUN7
    {"S_DSGUN8","SPR_SHT2","NULL","S_DSGUN9"},	// S_DSGUN8
    {"S_DSGUN9","SPR_SHT2","A_CloseShotgun2","S_DSGUN10"},	// S_DSGUN9
    {"S_DSGUN10","SPR_SHT2","A_ReFire","S_DSGUN"},	// S_DSGUN10
    {"S_DSNR1","SPR_SHT2","NULL","S_DSNR2"},	// S_DSNR1
    {"S_DSNR2","SPR_SHT2","NULL","S_DSGUNDOWN"},	// S_DSNR2
    {"S_DSGUNFLASH1","SPR_SHT2","A_Light1","S_DSGUNFLASH2"},	// S_DSGUNFLASH1
    {"S_DSGUNFLASH2","SPR_SHT2","A_Light2","S_LIGHTDONE"},	// S_DSGUNFLASH2
    {"S_CHAIN","SPR_CHGG","A_WeaponReady","S_CHAIN"},	// S_CHAIN
    {"S_CHAINDOWN","SPR_CHGG","A_Lower","S_CHAINDOWN"},	// S_CHAINDOWN
    {"S_CHAINUP","SPR_CHGG","A_Raise","S_CHAINUP"},	// S_CHAINUP
    {"S_CHAIN1","SPR_CHGG","A_FireCGun","S_CHAIN2"},	// S_CHAIN1
    {"S_CHAIN2","SPR_CHGG","A_FireCGun","S_CHAIN3"},	// S_CHAIN2
    {"S_CHAIN3","SPR_CHGG","A_ReFire","S_CHAIN"},	// S_CHAIN3
    {"S_CHAINFLASH1","SPR_CHGF","A_Light1","S_LIGHTDONE"},	// S_CHAINFLASH1
    {"S_CHAINFLASH2","SPR_CHGF","A_Light2","S_LIGHTDONE"},	// S_CHAINFLASH2
    {"S_MISSILE","SPR_MISG","A_WeaponReady","S_MISSILE"},	// S_MISSILE
    {"S_MISSILEDOWN","SPR_MISG","A_Lower","S_MISSILEDOWN"},	// S_MISSILEDOWN
    {"S_MISSILEUP","SPR_MISG","A_Raise","S_MISSILEUP"},	// S_MISSILEUP
    {"S_MISSILE1","SPR_MISG","A_GunFlash","S_MISSILE2"},	// S_MISSILE1
    {"S_MISSILE2","SPR_MISG","A_FireMissile","S_MISSILE3"},	// S_MISSILE2
    {"S_MISSILE3","SPR_MISG","A_ReFire","S_MISSILE"},	// S_MISSILE3
    {"S_MISSILEFLASH1","SPR_MISF","A_Light1","S_MISSILEFLASH2"},	// S_MISSILEFLASH1
    {"S_MISSILEFLASH2","SPR_MISF","NULL","S_MISSILEFLASH3"},	// S_MISSILEFLASH2
    {"S_MISSILEFLASH3","SPR_MISF","A_Light2","S_MISSILEFLASH4"},	// S_MISSILEFLASH3
    {"S_MISSILEFLASH4","SPR_MISF","A_Light2","S_LIGHTDONE"},	// S_MISSILEFLASH4
    {"S_SAW","SPR_SAWG","A_WeaponReady","S_SAWB"},	// S_SAW
    {"S_SAWB","SPR_SAWG","A_WeaponReady","S_SAW"},	// S_SAWB
    {"S_SAWDOWN","SPR_SAWG","A_Lower","S_SAWDOWN"},	// S_SAWDOWN
    {"S_SAWUP","SPR_SAWG","A_Raise","S_SAWUP"},	// S_SAWUP
    {"S_SAW1","SPR_SAWG","A_Saw","S_SAW2"},	// S_SAW1
    {"S_SAW2","SPR_SAWG","A_Saw","S_SAW3"},	// S_SAW2
    {"S_SAW3","SPR_SAWG","A_ReFire","S_SAW"},	// S_SAW3
    {"S_PLASMA","SPR_PLSG","A_WeaponReady","S_PLASMA"},	// S_PLASMA
    {"S_PLASMADOWN","SPR_PLSG","A_Lower","S_PLASMADOWN"},	// S_PLASMADOWN
    {"S_PLASMAUP","SPR_PLSG","A_Raise","S_PLASMAUP"},	// S_PLASMAUP
    {"S_PLASMA1","SPR_PLSG","A_FirePlasma","S_PLASMA2"},	// S_PLASMA1
    {"S_PLASMA2","SPR_PLSG","A_ReFire","S_PLASMA"},	// S_PLASMA2
    {"S_PLASMAFLASH1","SPR_PLSF","A_Light1","S_LIGHTDONE"},	// S_PLASMAFLASH1
    {"S_PLASMAFLASH2","SPR_PLSF","A_Light1","S_LIGHTDONE"},	// S_PLASMAFLASH2
    {"S_BFG","SPR_BFGG","A_WeaponReady","S_BFG"},	// S_BFG
    {"S_BFGDOWN","SPR_BFGG","A_Lower","S_BFGDOWN"},	// S_BFGDOWN
    {"S_BFGUP","SPR_BFGG","A_Raise","S_BFGUP"},	// S_BFGUP
    {"S_BFG1","SPR_BFGG","A_BFGsound","S_BFG2"},	// S_BFG1
    {"S_BFG2","SPR_BFGG","A_GunFlash","S_BFG3"},	// S_BFG2
    {"S_BFG3","SPR_BFGG","A_FireBFG","S_BFG4"},	// S_BFG3
    {"S_BFG4","SPR_BFGG","A_ReFire","S_BFG"},	// S_BFG4
    {"S_BFGFLASH1","SPR_BFGF","A_Light1","S_BFGFLASH2"},	// S_BFGFLASH1
    {"S_BFGFLASH2","SPR_BFGF","A_Light2","S_LIGHTDONE"},	// S_BFGFLASH2
    {"S_BLOOD1","SPR_BLUD","NULL","S_BLOOD2"},	// S_BLOOD1
    {"S_BLOOD2","SPR_BLUD","NULL","S_BLOOD3"},	// S_BLOOD2
    {"S_BLOOD3","SPR_BLUD","NULL","S_NULL"},	// S_BLOOD3
    {"S_PUFF1","SPR_PUFF","NULL","S_PUFF2"},	// S_PUFF1
    {"S_PUFF2","SPR_PUFF","NULL","S_PUFF3"},	// S_PUFF2
    {"S_PUFF3","SPR_PUFF","NULL","S_PUFF4"},	// S_PUFF3
    {"S_PUFF4","SPR_PUFF","NULL","S_NULL"},	// S_PUFF4
    {"S_TBALL1","SPR_BAL1","NULL","S_TBALL2"},	// S_TBALL1
    {"S_TBALL2","SPR_BAL1","NULL","S_TBALL1"},	// S_TBALL2
    {"S_TBALLX1","SPR_BAL1","NULL","S_TBALLX2"},	// S_TBALLX1
    {"S_TBALLX2","SPR_BAL1","NULL","S_TBALLX3"},	// S_TBALLX2
    {"S_TBALLX3","SPR_BAL1","NULL","S_NULL"},	// S_TBALLX3
    {"S_RBALL1","SPR_BAL2","NULL","S_RBALL2"},	// S_RBALL1
    {"S_RBALL2","SPR_BAL2","NULL","S_RBALL1"},	// S_RBALL2
    {"S_RBALLX1","SPR_BAL2","NULL","S_RBALLX2"},	// S_RBALLX1
    {"S_RBALLX2","SPR_BAL2","NULL","S_RBALLX3"},	// S_RBALLX2
    {"S_RBALLX3","SPR_BAL2","NULL","S_NULL"},	// S_RBALLX3
    {"S_PLASBALL","SPR_PLSS","NULL","S_PLASBALL2"},	// S_PLASBALL
    {"S_PLASBALL2","SPR_PLSS","NULL","S_PLASBALL"},	// S_PLASBALL2
    {"S_PLASEXP","SPR_PLSE","NULL","S_PLASEXP2"},	// S_PLASEXP
    {"S_PLASEXP2","SPR_PLSE","NULL","S_PLASEXP3"},	// S_PLASEXP2
    {"S_PLASEXP3","SPR_PLSE","NULL","S_PLASEXP4"},	// S_PLASEXP3
    {"S_PLASEXP4","SPR_PLSE","NULL","S_PLASEXP5"},	// S_PLASEXP4
    {"S_PLASEXP5","SPR_PLSE","NULL","S_NULL"},	// S_PLASEXP5
    {"S_ROCKET","SPR_MISL","NULL","S_ROCKET"},	// S_ROCKET
    {"S_BFGSHOT","SPR_BFS1","NULL","S_BFGSHOT2"},	// S_BFGSHOT
    {"S_BFGSHOT2","SPR_BFS1","NULL","S_BFGSHOT"},	// S_BFGSHOT2
    {"S_BFGLAND","SPR_BFE1","NULL","S_BFGLAND2"},	// S_BFGLAND
    {"S_BFGLAND2","SPR_BFE1","NULL","S_BFGLAND3"},	// S_BFGLAND2
    {"S_BFGLAND3","SPR_BFE1","A_BFGSpray","S_BFGLAND4"},	// S_BFGLAND3
    {"S_BFGLAND4","SPR_BFE1","NULL","S_BFGLAND5"},	// S_BFGLAND4
    {"S_BFGLAND5","SPR_BFE1","NULL","S_BFGLAND6"},	// S_BFGLAND5
    {"S_BFGLAND6","SPR_BFE1","NULL","S_NULL"},	// S_BFGLAND6
    {"S_BFGEXP","SPR_BFE2","NULL","S_BFGEXP2"},	// S_BFGEXP
    {"S_BFGEXP2","SPR_BFE2","NULL","S_BFGEXP3"},	// S_BFGEXP2
    {"S_BFGEXP3","SPR_BFE2","NULL","S_BFGEXP4"},	// S_BFGEXP3
    {"S_BFGEXP4","SPR_BFE2","NULL","S_NULL"},	// S_BFGEXP4
    {"S_EXPLODE1","SPR_MISL","A_Explode","S_EXPLODE2"},	// S_EXPLODE1
    {"S_EXPLODE2","SPR_MISL","NULL","S_EXPLODE3"},	// S_EXPLODE2
    {"S_EXPLODE3","SPR_MISL","NULL","S_NULL"},	// S_EXPLODE3
    {"S_TFOG","SPR_TFOG","NULL","S_TFOG01"},	// S_TFOG
    {"S_TFOG01","SPR_TFOG","NULL","S_TFOG02"},	// S_TFOG01
    {"S_TFOG02","SPR_TFOG","NULL","S_TFOG2"},	// S_TFOG02
    {"S_TFOG2","SPR_TFOG","NULL","S_TFOG3"},	// S_TFOG2
    {"S_TFOG3","SPR_TFOG","NULL","S_TFOG4"},	// S_TFOG3
    {"S_TFOG4","SPR_TFOG","NULL","S_TFOG5"},	// S_TFOG4
    {"S_TFOG5","SPR_TFOG","NULL","S_TFOG6"},	// S_TFOG5
    {"S_TFOG6","SPR_TFOG","NULL","S_TFOG7"},	// S_TFOG6
    {"S_TFOG7","SPR_TFOG","NULL","S_TFOG8"},	// S_TFOG7
    {"S_TFOG8","SPR_TFOG","NULL","S_TFOG9"},	// S_TFOG8
    {"S_TFOG9","SPR_TFOG","NULL","S_TFOG10"},	// S_TFOG9
    {"S_TFOG10","SPR_TFOG","NULL","S_NULL"},	// S_TFOG10
    {"S_IFOG","SPR_IFOG","NULL","S_IFOG01"},	// S_IFOG
    {"S_IFOG01","SPR_IFOG","NULL","S_IFOG02"},	// S_IFOG01
    {"S_IFOG02","SPR_IFOG","NULL","S_IFOG2"},	// S_IFOG02
    {"S_IFOG2","SPR_IFOG","NULL","S_IFOG3"},	// S_IFOG2
    {"S_IFOG3","SPR_IFOG","NULL","S_IFOG4"},	// S_IFOG3
    {"S_IFOG4","SPR_IFOG","NULL","S_IFOG5"},	// S_IFOG4
    {"S_IFOG5","SPR_IFOG","NULL","S_NULL"},	// S_IFOG5
    {"S_PLAY","SPR_PLAY","NULL","S_NULL"},	// S_PLAY
    {"S_PLAY_RUN1","SPR_PLAY","NULL","S_PLAY_RUN2"},	// S_PLAY_RUN1
    {"S_PLAY_RUN2","SPR_PLAY","NULL","S_PLAY_RUN3"},	// S_PLAY_RUN2
    {"S_PLAY_RUN3","SPR_PLAY","NULL","S_PLAY_RUN4"},	// S_PLAY_RUN3
    {"S_PLAY_RUN4","SPR_PLAY","NULL","S_PLAY_RUN1"},	// S_PLAY_RUN4
    {"S_PLAY_ATK1","SPR_PLAY","NULL","S_PLAY"},	// S_PLAY_ATK1
    {"S_PLAY_ATK2","SPR_PLAY","NULL","S_PLAY_ATK1"},	// S_PLAY_ATK2
    {"S_PLAY_PAIN","SPR_PLAY","NULL","S_PLAY_PAIN2"},	// S_PLAY_PAIN
    {"S_PLAY_PAIN2","SPR_PLAY","A_Pain","S_PLAY"},	// S_PLAY_PAIN2
    {"S_PLAY_DIE1","SPR_PLAY","NULL","S_PLAY_DIE2"},	// S_PLAY_DIE1
    {"S_PLAY_DIE2","SPR_PLAY","A_PlayerScream","S_PLAY_DIE3"},	// S_PLAY_DIE2
    {"S_PLAY_DIE3","SPR_PLAY","A_Fall","S_PLAY_DIE4"},	// S_PLAY_DIE3
    {"S_PLAY_DIE4","SPR_PLAY","NULL","S_PLAY_DIE5"},	// S_PLAY_DIE4
    {"S_PLAY_DIE5","SPR_PLAY","NULL","S_PLAY_DIE6"},	// S_PLAY_DIE5
    {"S_PLAY_DIE6","SPR_PLAY","NULL","S_PLAY_DIE7"},	// S_PLAY_DIE6
    {"S_PLAY_DIE7","SPR_PLAY","NULL","S_NULL"},	// S_PLAY_DIE7
    {"S_PLAY_XDIE1","SPR_PLAY","NULL","S_PLAY_XDIE2"},	// S_PLAY_XDIE1
    {"S_PLAY_XDIE2","SPR_PLAY","A_XScream","S_PLAY_XDIE3"},	// S_PLAY_XDIE2
    {"S_PLAY_XDIE3","SPR_PLAY","A_Fall","S_PLAY_XDIE4"},	// S_PLAY_XDIE3
    {"S_PLAY_XDIE4","SPR_PLAY","NULL","S_PLAY_XDIE5"},	// S_PLAY_XDIE4
    {"S_PLAY_XDIE5","SPR_PLAY","NULL","S_PLAY_XDIE6"},	// S_PLAY_XDIE5
    {"S_PLAY_XDIE6","SPR_PLAY","NULL","S_PLAY_XDIE7"},	// S_PLAY_XDIE6
    {"S_PLAY_XDIE7","SPR_PLAY","NULL","S_PLAY_XDIE8"},	// S_PLAY_XDIE7
    {"S_PLAY_XDIE8","SPR_PLAY","NULL","S_PLAY_XDIE9"},	// S_PLAY_XDIE8
    {"S_PLAY_XDIE9","SPR_PLAY","NULL","S_NULL"},	// S_PLAY_XDIE9
    {"S_POSS_STND","SPR_POSS","A_Look","S_POSS_STND2"},	// S_POSS_STND
    {"S_POSS_STND2","SPR_POSS","A_Look","S_POSS_STND"},	// S_POSS_STND2
    {"S_POSS_RUN1","SPR_POSS","A_Chase","S_POSS_RUN2"},	// S_POSS_RUN1
    {"S_POSS_RUN2","SPR_POSS","A_Chase","S_POSS_RUN3"},	// S_POSS_RUN2
    {"S_POSS_RUN3","SPR_POSS","A_Chase","S_POSS_RUN4"},	// S_POSS_RUN3
    {"S_POSS_RUN4","SPR_POSS","A_Chase","S_POSS_RUN5"},	// S_POSS_RUN4
    {"S_POSS_RUN5","SPR_POSS","A_Chase","S_POSS_RUN6"},	// S_POSS_RUN5
    {"S_POSS_RUN6","SPR_POSS","A_Chase","S_POSS_RUN7"},	// S_POSS_RUN6
    {"S_POSS_RUN7","SPR_POSS","A_Chase","S_POSS_RUN8"},	// S_POSS_RUN7
    {"S_POSS_RUN8","SPR_POSS","A_Chase","S_POSS_RUN1"},	// S_POSS_RUN8
    {"S_POSS_ATK1","SPR_POSS","A_FaceTarget","S_POSS_ATK2"},	// S_POSS_ATK1
    {"S_POSS_ATK2","SPR_POSS","A_PosAttack","S_POSS_ATK3"},	// S_POSS_ATK2
    {"S_POSS_ATK3","SPR_POSS","NULL","S_POSS_RUN1"},	// S_POSS_ATK3
    {"S_POSS_PAIN","SPR_POSS","NULL","S_POSS_PAIN2"},	// S_POSS_PAIN
    {"S_POSS_PAIN2","SPR_POSS","A_Pain","S_POSS_RUN1"},	// S_POSS_PAIN2
    {"S_POSS_DIE1","SPR_POSS","NULL","S_POSS_DIE2"},	// S_POSS_DIE1
    {"S_POSS_DIE2","SPR_POSS","A_Scream","S_POSS_DIE3"},	// S_POSS_DIE2
    {"S_POSS_DIE3","SPR_POSS","A_Fall","S_POSS_DIE4"},	// S_POSS_DIE3
    {"S_POSS_DIE4","SPR_POSS","NULL","S_POSS_DIE5"},	// S_POSS_DIE4
    {"S_POSS_DIE5","SPR_POSS","NULL","S_NULL"},	// S_POSS_DIE5
    {"S_POSS_XDIE1","SPR_POSS","NULL","S_POSS_XDIE2"},	// S_POSS_XDIE1
    {"S_POSS_XDIE2","SPR_POSS","A_XScream","S_POSS_XDIE3"},	// S_POSS_XDIE2
    {"S_POSS_XDIE3","SPR_POSS","A_Fall","S_POSS_XDIE4"},	// S_POSS_XDIE3
    {"S_POSS_XDIE4","SPR_POSS","NULL","S_POSS_XDIE5"},	// S_POSS_XDIE4
    {"S_POSS_XDIE5","SPR_POSS","NULL","S_POSS_XDIE6"},	// S_POSS_XDIE5
    {"S_POSS_XDIE6","SPR_POSS","NULL","S_POSS_XDIE7"},	// S_POSS_XDIE6
    {"S_POSS_XDIE7","SPR_POSS","NULL","S_POSS_XDIE8"},	// S_POSS_XDIE7
    {"S_POSS_XDIE8","SPR_POSS","NULL","S_POSS_XDIE9"},	// S_POSS_XDIE8
    {"S_POSS_XDIE9","SPR_POSS","NULL","S_NULL"},	// S_POSS_XDIE9
    {"S_POSS_RAISE1","SPR_POSS","NULL","S_POSS_RAISE2"},	// S_POSS_RAISE1
    {"S_POSS_RAISE2","SPR_POSS","NULL","S_POSS_RAISE3"},	// S_POSS_RAISE2
    {"S_POSS_RAISE3","SPR_POSS","NULL","S_POSS_RAISE4"},	// S_POSS_RAISE3
    {"S_POSS_RAISE4","SPR_POSS","NULL","S_POSS_RUN1"},	// S_POSS_RAISE4
    {"S_SPOS_STND","SPR_SPOS","A_Look","S_SPOS_STND2"},	// S_SPOS_STND
    {"S_SPOS_STND2","SPR_SPOS","A_Look","S_SPOS_STND"},	// S_SPOS_STND2
    {"S_SPOS_RUN1","SPR_SPOS","A_Chase","S_SPOS_RUN2"},	// S_SPOS_RUN1
    {"S_SPOS_RUN2","SPR_SPOS","A_Chase","S_SPOS_RUN3"},	// S_SPOS_RUN2
    {"S_SPOS_RUN3","SPR_SPOS","A_Chase","S_SPOS_RUN4"},	// S_SPOS_RUN3
    {"S_SPOS_RUN4","SPR_SPOS","A_Chase","S_SPOS_RUN5"},	// S_SPOS_RUN4
    {"S_SPOS_RUN5","SPR_SPOS","A_Chase","S_SPOS_RUN6"},	// S_SPOS_RUN5
    {"S_SPOS_RUN6","SPR_SPOS","A_Chase","S_SPOS_RUN7"},	// S_SPOS_RUN6
    {"S_SPOS_RUN7","SPR_SPOS","A_Chase","S_SPOS_RUN8"},	// S_SPOS_RUN7
    {"S_SPOS_RUN8","SPR_SPOS","A_Chase","S_SPOS_RUN1"},	// S_SPOS_RUN8
    {"S_SPOS_ATK1","SPR_SPOS","A_FaceTarget","S_SPOS_ATK2"},	// S_SPOS_ATK1
    {"S_SPOS_ATK2","SPR_SPOS","A_SPosAttack","S_SPOS_ATK3"},	// S_SPOS_ATK2
    {"S_SPOS_ATK3","SPR_SPOS","NULL","S_SPOS_RUN1"},	// S_SPOS_ATK3
    {"S_SPOS_PAIN","SPR_SPOS","NULL","S_SPOS_PAIN2"},	// S_SPOS_PAIN
    {"S_SPOS_PAIN2","SPR_SPOS","A_Pain","S_SPOS_RUN1"},	// S_SPOS_PAIN2
    {"S_SPOS_DIE1","SPR_SPOS","NULL","S_SPOS_DIE2"},	// S_SPOS_DIE1
    {"S_SPOS_DIE2","SPR_SPOS","A_Scream","S_SPOS_DIE3"},	// S_SPOS_DIE2
    {"S_SPOS_DIE3","SPR_SPOS","A_Fall","S_SPOS_DIE4"},	// S_SPOS_DIE3
    {"S_SPOS_DIE4","SPR_SPOS","NULL","S_SPOS_DIE5"},	// S_SPOS_DIE4
    {"S_SPOS_DIE5","SPR_SPOS","NULL","S_NULL"},	// S_SPOS_DIE5
    {"S_SPOS_XDIE1","SPR_SPOS","NULL","S_SPOS_XDIE2"},	// S_SPOS_XDIE1
    {"S_SPOS_XDIE2","SPR_SPOS","A_XScream","S_SPOS_XDIE3"},	// S_SPOS_XDIE2
    {"S_SPOS_XDIE3","SPR_SPOS","A_Fall","S_SPOS_XDIE4"},	// S_SPOS_XDIE3
    {"S_SPOS_XDIE4","SPR_SPOS","NULL","S_SPOS_XDIE5"},	// S_SPOS_XDIE4
    {"S_SPOS_XDIE5","SPR_SPOS","NULL","S_SPOS_XDIE6"},	// S_SPOS_XDIE5
    {"S_SPOS_XDIE6","SPR_SPOS","NULL","S_SPOS_XDIE7"},	// S_SPOS_XDIE6
    {"S_SPOS_XDIE7","SPR_SPOS","NULL","S_SPOS_XDIE8"},	// S_SPOS_XDIE7
    {"S_SPOS_XDIE8","SPR_SPOS","NULL","S_SPOS_XDIE9"},	// S_SPOS_XDIE8
    {"S_SPOS_XDIE9","SPR_SPOS","NULL","S_NULL"},	// S_SPOS_XDIE9
    {"S_SPOS_RAISE1","SPR_SPOS","NULL","S_SPOS_RAISE2"},	// S_SPOS_RAISE1
    {"S_SPOS_RAISE2","SPR_SPOS","NULL","S_SPOS_RAISE3"},	// S_SPOS_RAISE2
    {"S_SPOS_RAISE3","SPR_SPOS","NULL","S_SPOS_RAISE4"},	// S_SPOS_RAISE3
    {"S_SPOS_RAISE4","SPR_SPOS","NULL","S_SPOS_RAISE5"},	// S_SPOS_RAISE4
    {"S_SPOS_RAISE5","SPR_SPOS","NULL","S_SPOS_RUN1"},	// S_SPOS_RAISE5
    {"S_VILE_STND","SPR_VILE","A_Look","S_VILE_STND2"},	// S_VILE_STND
    {"S_VILE_STND2","SPR_VILE","A_Look","S_VILE_STND"},	// S_VILE_STND2
    {"S_VILE_RUN1","SPR_VILE","A_VileChase","S_VILE_RUN2"},	// S_VILE_RUN1
    {"S_VILE_RUN2","SPR_VILE","A_VileChase","S_VILE_RUN3"},	// S_VILE_RUN2
    {"S_VILE_RUN3","SPR_VILE","A_VileChase","S_VILE_RUN4"},	// S_VILE_RUN3
    {"S_VILE_RUN4","SPR_VILE","A_VileChase","S_VILE_RUN5"},	// S_VILE_RUN4
    {"S_VILE_RUN5","SPR_VILE","A_VileChase","S_VILE_RUN6"},	// S_VILE_RUN5
    {"S_VILE_RUN6","SPR_VILE","A_VileChase","S_VILE_RUN7"},	// S_VILE_RUN6
    {"S_VILE_RUN7","SPR_VILE","A_VileChase","S_VILE_RUN8"},	// S_VILE_RUN7
    {"S_VILE_RUN8","SPR_VILE","A_VileChase","S_VILE_RUN9"},	// S_VILE_RUN8
    {"S_VILE_RUN9","SPR_VILE","A_VileChase","S_VILE_RUN10"},	// S_VILE_RUN9
    {"S_VILE_RUN10","SPR_VILE","A_VileChase","S_VILE_RUN11"},	// S_VILE_RUN10
    {"S_VILE_RUN11","SPR_VILE","A_VileChase","S_VILE_RUN12"},	// S_VILE_RUN11
    {"S_VILE_RUN12","SPR_VILE","A_VileChase","S_VILE_RUN1"},	// S_VILE_RUN12
    {"S_VILE_ATK1","SPR_VILE","A_VileStart","S_VILE_ATK2"},	// S_VILE_ATK1
    {"S_VILE_ATK2","SPR_VILE","A_FaceTarget","S_VILE_ATK3"},	// S_VILE_ATK2
    {"S_VILE_ATK3","SPR_VILE","A_VileTarget","S_VILE_ATK4"},	// S_VILE_ATK3
    {"S_VILE_ATK4","SPR_VILE","A_FaceTarget","S_VILE_ATK5"},	// S_VILE_ATK4
    {"S_VILE_ATK5","SPR_VILE","A_FaceTarget","S_VILE_ATK6"},	// S_VILE_ATK5
    {"S_VILE_ATK6","SPR_VILE","A_FaceTarget","S_VILE_ATK7"},	// S_VILE_ATK6
    {"S_VILE_ATK7","SPR_VILE","A_FaceTarget","S_VILE_ATK8"},	// S_VILE_ATK7
    {"S_VILE_ATK8","SPR_VILE","A_FaceTarget","S_VILE_ATK9"},	// S_VILE_ATK8
    {"S_VILE_ATK9","SPR_VILE","A_FaceTarget","S_VILE_ATK10"},	// S_VILE_ATK9
    {"S_VILE_ATK10","SPR_VILE","A_VileAttack","S_VILE_ATK11"},	// S_VILE_ATK10
    {"S_VILE_ATK11","SPR_VILE","NULL","S_VILE_RUN1"},	// S_VILE_ATK11
    {"S_VILE_HEAL1","SPR_VILE","NULL","S_VILE_HEAL2"},	// S_VILE_HEAL1
    {"S_VILE_HEAL2","SPR_VILE","NULL","S_VILE_HEAL3"},	// S_VILE_HEAL2
    {"S_VILE_HEAL3","SPR_VILE","NULL","S_VILE_RUN1"},	// S_VILE_HEAL3
    {"S_VILE_PAIN","SPR_VILE","NULL","S_VILE_PAIN2"},	// S_VILE_PAIN
    {"S_VILE_PAIN2","SPR_VILE","A_Pain","S_VILE_RUN1"},	// S_VILE_PAIN2
    {"S_VILE_DIE1","SPR_VILE","NULL","S_VILE_DIE2"},	// S_VILE_DIE1
    {"S_VILE_DIE2","SPR_VILE","A_Scream","S_VILE_DIE3"},	// S_VILE_DIE2
    {"S_VILE_DIE3","SPR_VILE","A_Fall","S_VILE_DIE4"},	// S_VILE_DIE3
    {"S_VILE_DIE4","SPR_VILE","NULL","S_VILE_DIE5"},	// S_VILE_DIE4
    {"S_VILE_DIE5","SPR_VILE","NULL","S_VILE_DIE6"},	// S_VILE_DIE5
    {"S_VILE_DIE6","SPR_VILE","NULL","S_VILE_DIE7"},	// S_VILE_DIE6
    {"S_VILE_DIE7","SPR_VILE","NULL","S_VILE_DIE8"},	// S_VILE_DIE7
    {"S_VILE_DIE8","SPR_VILE","NULL","S_VILE_DIE9"},	// S_VILE_DIE8
    {"S_VILE_DIE9","SPR_VILE","NULL","S_VILE_DIE10"},	// S_VILE_DIE9
    {"S_VILE_DIE10","SPR_VILE","NULL","S_NULL"},	// S_VILE_DIE10
    {"S_FIRE1","SPR_FIRE","A_StartFire","S_FIRE2"},	// S_FIRE1
    {"S_FIRE2","SPR_FIRE","A_Fire","S_FIRE3"},	// S_FIRE2
    {"S_FIRE3","SPR_FIRE","A_Fire","S_FIRE4"},	// S_FIRE3
    {"S_FIRE4","SPR_FIRE","A_Fire","S_FIRE5"},	// S_FIRE4
    {"S_FIRE5","SPR_FIRE","A_FireCrackle","S_FIRE6"},	// S_FIRE5
    {"S_FIRE6","SPR_FIRE","A_Fire","S_FIRE7"},	// S_FIRE6
    {"S_FIRE7","SPR_FIRE","A_Fire","S_FIRE8"},	// S_FIRE7
    {"S_FIRE8","SPR_FIRE","A_Fire","S_FIRE9"},	// S_FIRE8
    {"S_FIRE9","SPR_FIRE","A_Fire","S_FIRE10"},	// S_FIRE9
    {"S_FIRE10","SPR_FIRE","A_Fire","S_FIRE11"},	// S_FIRE10
    {"S_FIRE11","SPR_FIRE","A_Fire","S_FIRE12"},	// S_FIRE11
    {"S_FIRE12","SPR_FIRE","A_Fire","S_FIRE13"},	// S_FIRE12
    {"S_FIRE13","SPR_FIRE","A_Fire","S_FIRE14"},	// S_FIRE13
    {"S_FIRE14","SPR_FIRE","A_Fire","S_FIRE15"},	// S_FIRE14
    {"S_FIRE15","SPR_FIRE","A_Fire","S_FIRE16"},	// S_FIRE15
    {"S_FIRE16","SPR_FIRE","A_Fire","S_FIRE17"},	// S_FIRE16
    {"S_FIRE17","SPR_FIRE","A_Fire","S_FIRE18"},	// S_FIRE17
    {"S_FIRE18","SPR_FIRE","A_Fire","S_FIRE19"},	// S_FIRE18
    {"S_FIRE19","SPR_FIRE","A_FireCrackle","S_FIRE20"},	// S_FIRE19
    {"S_FIRE20","SPR_FIRE","A_Fire","S_FIRE21"},	// S_FIRE20
    {"S_FIRE21","SPR_FIRE","A_Fire","S_FIRE22"},	// S_FIRE21
    {"S_FIRE22","SPR_FIRE","A_Fire","S_FIRE23"},	// S_FIRE22
    {"S_FIRE23","SPR_FIRE","A_Fire","S_FIRE24"},	// S_FIRE23
    {"S_FIRE24","SPR_FIRE","A_Fire","S_FIRE25"},	// S_FIRE24
    {"S_FIRE25","SPR_FIRE","A_Fire","S_FIRE26"},	// S_FIRE25
    {"S_FIRE26","SPR_FIRE","A_Fire","S_FIRE27"},	// S_FIRE26
    {"S_FIRE27","SPR_FIRE","A_Fire","S_FIRE28"},	// S_FIRE27
    {"S_FIRE28","SPR_FIRE","A_Fire","S_FIRE29"},	// S_FIRE28
    {"S_FIRE29","SPR_FIRE","A_Fire","S_FIRE30"},	// S_FIRE29
    {"S_FIRE30","SPR_FIRE","A_Fire","S_NULL"},	// S_FIRE30
    {"S_SMOKE1","SPR_PUFF","NULL","S_SMOKE2"},	// S_SMOKE1
    {"S_SMOKE2","SPR_PUFF","NULL","S_SMOKE3"},	// S_SMOKE2
    {"S_SMOKE3","SPR_PUFF","NULL","S_SMOKE4"},	// S_SMOKE3
    {"S_SMOKE4","SPR_PUFF","NULL","S_SMOKE5"},	// S_SMOKE4
    {"S_SMOKE5","SPR_PUFF","NULL","S_NULL"},	// S_SMOKE5
    {"S_TRACER","SPR_FATB","A_Tracer","S_TRACER2"},	// S_TRACER
    {"S_TRACER2","SPR_FATB","A_Tracer","S_TRACER"},	// S_TRACER2
    {"S_TRACEEXP1","SPR_FBXP","NULL","S_TRACEEXP2"},	// S_TRACEEXP1
    {"S_TRACEEXP2","SPR_FBXP","NULL","S_TRACEEXP3"},	// S_TRACEEXP2
    {"S_TRACEEXP3","SPR_FBXP","NULL","S_NULL"},	// S_TRACEEXP3
    {"S_SKEL_STND","SPR_SKEL","A_Look","S_SKEL_STND2"},	// S_SKEL_STND
    {"S_SKEL_STND2","SPR_SKEL","A_Look","S_SKEL_STND"},	// S_SKEL_STND2
    {"S_SKEL_RUN1","SPR_SKEL","A_Chase","S_SKEL_RUN2"},	// S_SKEL_RUN1
    {"S_SKEL_RUN2","SPR_SKEL","A_Chase","S_SKEL_RUN3"},	// S_SKEL_RUN2
    {"S_SKEL_RUN3","SPR_SKEL","A_Chase","S_SKEL_RUN4"},	// S_SKEL_RUN3
    {"S_SKEL_RUN4","SPR_SKEL","A_Chase","S_SKEL_RUN5"},	// S_SKEL_RUN4
    {"S_SKEL_RUN5","SPR_SKEL","A_Chase","S_SKEL_RUN6"},	// S_SKEL_RUN5
    {"S_SKEL_RUN6","SPR_SKEL","A_Chase","S_SKEL_RUN7"},	// S_SKEL_RUN6
    {"S_SKEL_RUN7","SPR_SKEL","A_Chase","S_SKEL_RUN8"},	// S_SKEL_RUN7
    {"S_SKEL_RUN8","SPR_SKEL","A_Chase","S_SKEL_RUN9"},	// S_SKEL_RUN8
    {"S_SKEL_RUN9","SPR_SKEL","A_Chase","S_SKEL_RUN10"},	// S_SKEL_RUN9
    {"S_SKEL_RUN10","SPR_SKEL","A_Chase","S_SKEL_RUN11"},	// S_SKEL_RUN10
    {"S_SKEL_RUN11","SPR_SKEL","A_Chase","S_SKEL_RUN12"},	// S_SKEL_RUN11
    {"S_SKEL_RUN12","SPR_SKEL","A_Chase","S_SKEL_RUN1"},	// S_SKEL_RUN12
    {"S_SKEL_FIST1","SPR_SKEL","A_FaceTarget","S_SKEL_FIST2"},	// S_SKEL_FIST1
    {"S_SKEL_FIST2","SPR_SKEL","A_SkelWhoosh","S_SKEL_FIST3"},	// S_SKEL_FIST2
    {"S_SKEL_FIST3","SPR_SKEL","A_FaceTarget","S_SKEL_FIST4"},	// S_SKEL_FIST3
    {"S_SKEL_FIST4","SPR_SKEL","A_SkelFist","S_SKEL_RUN1"},	// S_SKEL_FIST4
    {"S_SKEL_MISS1","SPR_SKEL","A_FaceTarget","S_SKEL_MISS2"},	// S_SKEL_MISS1
    {"S_SKEL_MISS2","SPR_SKEL","A_FaceTarget","S_SKEL_MISS3"},	// S_SKEL_MISS2
    {"S_SKEL_MISS3","SPR_SKEL","A_SkelMissile","S_SKEL_MISS4"},	// S_SKEL_MISS3
    {"S_SKEL_MISS4","SPR_SKEL","A_FaceTarget","S_SKEL_RUN1"},	// S_SKEL_MISS4
    {"S_SKEL_PAIN","SPR_SKEL","NULL","S_SKEL_PAIN2"},	// S_SKEL_PAIN
    {"S_SKEL_PAIN2","SPR_SKEL","A_Pain","S_SKEL_RUN1"},	// S_SKEL_PAIN2
    {"S_SKEL_DIE1","SPR_SKEL","NULL","S_SKEL_DIE2"},	// S_SKEL_DIE1
    {"S_SKEL_DIE2","SPR_SKEL","NULL","S_SKEL_DIE3"},	// S_SKEL_DIE2
    {"S_SKEL_DIE3","SPR_SKEL","A_Scream","S_SKEL_DIE4"},	// S_SKEL_DIE3
    {"S_SKEL_DIE4","SPR_SKEL","A_Fall","S_SKEL_DIE5"},	// S_SKEL_DIE4
    {"S_SKEL_DIE5","SPR_SKEL","NULL","S_SKEL_DIE6"},	// S_SKEL_DIE5
    {"S_SKEL_DIE6","SPR_SKEL","NULL","S_NULL"},	// S_SKEL_DIE6
    {"S_SKEL_RAISE1","SPR_SKEL","NULL","S_SKEL_RAISE2"},	// S_SKEL_RAISE1
    {"S_SKEL_RAISE2","SPR_SKEL","NULL","S_SKEL_RAISE3"},	// S_SKEL_RAISE2
    {"S_SKEL_RAISE3","SPR_SKEL","NULL","S_SKEL_RAISE4"},	// S_SKEL_RAISE3
    {"S_SKEL_RAISE4","SPR_SKEL","NULL","S_SKEL_RAISE5"},	// S_SKEL_RAISE4
    {"S_SKEL_RAISE5","SPR_SKEL","NULL","S_SKEL_RAISE6"},	// S_SKEL_RAISE5
    {"S_SKEL_RAISE6","SPR_SKEL","NULL","S_SKEL_RUN1"},	// S_SKEL_RAISE6
    {"S_FATSHOT1","SPR_MANF","NULL","S_FATSHOT2"},	// S_FATSHOT1
    {"S_FATSHOT2","SPR_MANF","NULL","S_FATSHOT1"},	// S_FATSHOT2
    {"S_FATSHOTX1","SPR_MISL","NULL","S_FATSHOTX2"},	// S_FATSHOTX1
    {"S_FATSHOTX2","SPR_MISL","NULL","S_FATSHOTX3"},	// S_FATSHOTX2
    {"S_FATSHOTX3","SPR_MISL","NULL","S_NULL"},	// S_FATSHOTX3
    {"S_FATT_STND","SPR_FATT","A_Look","S_FATT_STND2"},	// S_FATT_STND
    {"S_FATT_STND2","SPR_FATT","A_Look","S_FATT_STND"},	// S_FATT_STND2
    {"S_FATT_RUN1","SPR_FATT","A_Chase","S_FATT_RUN2"},	// S_FATT_RUN1
    {"S_FATT_RUN2","SPR_FATT","A_Chase","S_FATT_RUN3"},	// S_FATT_RUN2
    {"S_FATT_RUN3","SPR_FATT","A_Chase","S_FATT_RUN4"},	// S_FATT_RUN3
    {"S_FATT_RUN4","SPR_FATT","A_Chase","S_FATT_RUN5"},	// S_FATT_RUN4
    {"S_FATT_RUN5","SPR_FATT","A_Chase","S_FATT_RUN6"},	// S_FATT_RUN5
    {"S_FATT_RUN6","SPR_FATT","A_Chase","S_FATT_RUN7"},	// S_FATT_RUN6
    {"S_FATT_RUN7","SPR_FATT","A_Chase","S_FATT_RUN8"},	// S_FATT_RUN7
    {"S_FATT_RUN8","SPR_FATT","A_Chase","S_FATT_RUN9"},	// S_FATT_RUN8
    {"S_FATT_RUN9","SPR_FATT","A_Chase","S_FATT_RUN10"},	// S_FATT_RUN9
    {"S_FATT_RUN10","SPR_FATT","A_Chase","S_FATT_RUN11"},	// S_FATT_RUN10
    {"S_FATT_RUN11","SPR_FATT","A_Chase","S_FATT_RUN12"},	// S_FATT_RUN11
    {"S_FATT_RUN12","SPR_FATT","A_Chase","S_FATT_RUN1"},	// S_FATT_RUN12
    {"S_FATT_ATK1","SPR_FATT","A_FatRaise","S_FATT_ATK2"},	// S_FATT_ATK1
    {"S_FATT_ATK2","SPR_FATT","A_FatAttack1","S_FATT_ATK3"},	// S_FATT_ATK2
    {"S_FATT_ATK3","SPR_FATT","A_FaceTarget","S_FATT_ATK4"},	// S_FATT_ATK3
    {"S_FATT_ATK4","SPR_FATT","A_FaceTarget","S_FATT_ATK5"},	// S_FATT_ATK4
    {"S_FATT_ATK5","SPR_FATT","A_FatAttack2","S_FATT_ATK6"},	// S_FATT_ATK5
    {"S_FATT_ATK6","SPR_FATT","A_FaceTarget","S_FATT_ATK7"},	// S_FATT_ATK6
    {"S_FATT_ATK7","SPR_FATT","A_FaceTarget","S_FATT_ATK8"},	// S_FATT_ATK7
    {"S_FATT_ATK8","SPR_FATT","A_FatAttack3","S_FATT_ATK9"},	// S_FATT_ATK8
    {"S_FATT_ATK9","SPR_FATT","A_FaceTarget","S_FATT_ATK10"},	// S_FATT_ATK9
    {"S_FATT_ATK10","SPR_FATT","A_FaceTarget","S_FATT_RUN1"},	// S_FATT_ATK10
    {"S_FATT_PAIN","SPR_FATT","NULL","S_FATT_PAIN2"},	// S_FATT_PAIN
    {"S_FATT_PAIN2","SPR_FATT","A_Pain","S_FATT_RUN1"},	// S_FATT_PAIN2
    {"S_FATT_DIE1","SPR_FATT","NULL","S_FATT_DIE2"},	// S_FATT_DIE1
    {"S_FATT_DIE2","SPR_FATT","A_Scream","S_FATT_DIE3"},	// S_FATT_DIE2
    {"S_FATT_DIE3","SPR_FATT","A_Fall","S_FATT_DIE4"},	// S_FATT_DIE3
    {"S_FATT_DIE4","SPR_FATT","NULL","S_FATT_DIE5"},	// S_FATT_DIE4
    {"S_FATT_DIE5","SPR_FATT","NULL","S_FATT_DIE6"},	// S_FATT_DIE5
    {"S_FATT_DIE6","SPR_FATT","NULL","S_FATT_DIE7"},	// S_FATT_DIE6
    {"S_FATT_DIE7","SPR_FATT","NULL","S_FATT_DIE8"},	// S_FATT_DIE7
    {"S_FATT_DIE8","SPR_FATT","NULL","S_FATT_DIE9"},	// S_FATT_DIE8
    {"S_FATT_DIE9","SPR_FATT","NULL","S_FATT_DIE10"},	// S_FATT_DIE9
    {"S_FATT_DIE10","SPR_FATT","A_BossDeath","S_NULL"},	// S_FATT_DIE10
    {"S_FATT_RAISE1","SPR_FATT","NULL","S_FATT_RAISE2"},	// S_FATT_RAISE1
    {"S_FATT_RAISE2","SPR_FATT","NULL","S_FATT_RAISE3"},	// S_FATT_RAISE2
    {"S_FATT_RAISE3","SPR_FATT","NULL","S_FATT_RAISE4"},	// S_FATT_RAISE3
    {"S_FATT_RAISE4","SPR_FATT","NULL","S_FATT_RAISE5"},	// S_FATT_RAISE4
    {"S_FATT_RAISE5","SPR_FATT","NULL","S_FATT_RAISE6"},	// S_FATT_RAISE5
    {"S_FATT_RAISE6","SPR_FATT","NULL","S_FATT_RAISE7"},	// S_FATT_RAISE6
    {"S_FATT_RAISE7","SPR_FATT","NULL","S_FATT_RAISE8"},	// S_FATT_RAISE7
    {"S_FATT_RAISE8","SPR_FATT","NULL","S_FATT_RUN1"},	// S_FATT_RAISE8
    {"S_CPOS_STND","SPR_CPOS","A_Look","S_CPOS_STND2"},	// S_CPOS_STND
    {"S_CPOS_STND2","SPR_CPOS","A_Look","S_CPOS_STND"},	// S_CPOS_STND2
    {"S_CPOS_RUN1","SPR_CPOS","A_Chase","S_CPOS_RUN2"},	// S_CPOS_RUN1
    {"S_CPOS_RUN2","SPR_CPOS","A_Chase","S_CPOS_RUN3"},	// S_CPOS_RUN2
    {"S_CPOS_RUN3","SPR_CPOS","A_Chase","S_CPOS_RUN4"},	// S_CPOS_RUN3
    {"S_CPOS_RUN4","SPR_CPOS","A_Chase","S_CPOS_RUN5"},	// S_CPOS_RUN4
    {"S_CPOS_RUN5","SPR_CPOS","A_Chase","S_CPOS_RUN6"},	// S_CPOS_RUN5
    {"S_CPOS_RUN6","SPR_CPOS","A_Chase","S_CPOS_RUN7"},	// S_CPOS_RUN6
    {"S_CPOS_RUN7","SPR_CPOS","A_Chase","S_CPOS_RUN8"},	// S_CPOS_RUN7
    {"S_CPOS_RUN8","SPR_CPOS","A_Chase","S_CPOS_RUN1"},	// S_CPOS_RUN8
    {"S_CPOS_ATK1","SPR_CPOS","A_FaceTarget","S_CPOS_ATK2"},	// S_CPOS_ATK1
    {"S_CPOS_ATK2","SPR_CPOS","A_CPosAttack","S_CPOS_ATK3"},	// S_CPOS_ATK2
    {"S_CPOS_ATK3","SPR_CPOS","A_CPosAttack","S_CPOS_ATK4"},	// S_CPOS_ATK3
    {"S_CPOS_ATK4","SPR_CPOS","A_CPosRefire","S_CPOS_ATK2"},	// S_CPOS_ATK4
    {"S_CPOS_PAIN","SPR_CPOS","NULL","S_CPOS_PAIN2"},	// S_CPOS_PAIN
    {"S_CPOS_PAIN2","SPR_CPOS","A_Pain","S_CPOS_RUN1"},	// S_CPOS_PAIN2
    {"S_CPOS_DIE1","SPR_CPOS","NULL","S_CPOS_DIE2"},	// S_CPOS_DIE1
    {"S_CPOS_DIE2","SPR_CPOS","A_Scream","S_CPOS_DIE3"},	// S_CPOS_DIE2
    {"S_CPOS_DIE3","SPR_CPOS","A_Fall","S_CPOS_DIE4"},	// S_CPOS_DIE3
    {"S_CPOS_DIE4","SPR_CPOS","NULL","S_CPOS_DIE5"},	// S_CPOS_DIE4
    {"S_CPOS_DIE5","SPR_CPOS","NULL","S_CPOS_DIE6"},	// S_CPOS_DIE5
    {"S_CPOS_DIE6","SPR_CPOS","NULL","S_CPOS_DIE7"},	// S_CPOS_DIE6
    {"S_CPOS_DIE7","SPR_CPOS","NULL","S_NULL"},	// S_CPOS_DIE7
    {"S_CPOS_XDIE1","SPR_CPOS","NULL","S_CPOS_XDIE2"},	// S_CPOS_XDIE1
    {"S_CPOS_XDIE2","SPR_CPOS","A_XScream","S_CPOS_XDIE3"},	// S_CPOS_XDIE2
    {"S_CPOS_XDIE3","SPR_CPOS","A_Fall","S_CPOS_XDIE4"},	// S_CPOS_XDIE3
    {"S_CPOS_XDIE4","SPR_CPOS","NULL","S_CPOS_XDIE5"},	// S_CPOS_XDIE4
    {"S_CPOS_XDIE5","SPR_CPOS","NULL","S_CPOS_XDIE6"},	// S_CPOS_XDIE5
    {"S_CPOS_XDIE6","SPR_CPOS","NULL","S_NULL"},	// S_CPOS_XDIE6
    {"S_CPOS_RAISE1","SPR_CPOS","NULL","S_CPOS_RAISE2"},	// S_CPOS_RAISE1
    {"S_CPOS_RAISE2","SPR_CPOS","NULL","S_CPOS_RAISE3"},	// S_CPOS_RAISE2
    {"S_CPOS_RAISE3","SPR_CPOS","NULL","S_CPOS_RAISE4"},	// S_CPOS_RAISE3
    {"S_CPOS_RAISE4","SPR_CPOS","NULL","S_CPOS_RAISE5"},	// S_CPOS_RAISE4
    {"S_CPOS_RAISE5","SPR_CPOS","NULL","S_CPOS_RAISE6"},	// S_CPOS_RAISE5
    {"S_CPOS_RAISE6","SPR_CPOS","NULL","S_CPOS_RAISE7"},	// S_CPOS_RAISE6
    {"S_CPOS_RAISE7","SPR_CPOS","NULL","S_CPOS_RUN1"},	// S_CPOS_RAISE7
    {"S_TROO_STND","SPR_TROO","A_Look","S_TROO_STND2"},	// S_TROO_STND
    {"S_TROO_STND2","SPR_TROO","A_Look","S_TROO_STND"},	// S_TROO_STND2
    {"S_TROO_RUN1","SPR_TROO","A_Chase","S_TROO_RUN2"},	// S_TROO_RUN1
    {"S_TROO_RUN2","SPR_TROO","A_Chase","S_TROO_RUN3"},	// S_TROO_RUN2
    {"S_TROO_RUN3","SPR_TROO","A_Chase","S_TROO_RUN4"},	// S_TROO_RUN3
    {"S_TROO_RUN4","SPR_TROO","A_Chase","S_TROO_RUN5"},	// S_TROO_RUN4
    {"S_TROO_RUN5","SPR_TROO","A_Chase","S_TROO_RUN6"},	// S_TROO_RUN5
    {"S_TROO_RUN6","SPR_TROO","A_Chase","S_TROO_RUN7"},	// S_TROO_RUN6
    {"S_TROO_RUN7","SPR_TROO","A_Chase","S_TROO_RUN8"},	// S_TROO_RUN7
    {"S_TROO_RUN8","SPR_TROO","A_Chase","S_TROO_RUN1"},	// S_TROO_RUN8
    {"S_TROO_ATK1","SPR_TROO","A_FaceTarget","S_TROO_ATK2"},	// S_TROO_ATK1
    {"S_TROO_ATK2","SPR_TROO","A_FaceTarget","S_TROO_ATK3"},	// S_TROO_ATK2
    {"S_TROO_ATK3","SPR_TROO","A_TroopAttack","S_TROO_RUN1"},	// S_TROO_ATK3
    {"S_TROO_PAIN","SPR_TROO","NULL","S_TROO_PAIN2"},	// S_TROO_PAIN
    {"S_TROO_PAIN2","SPR_TROO","A_Pain","S_TROO_RUN1"},	// S_TROO_PAIN2
    {"S_TROO_DIE1","SPR_TROO","NULL","S_TROO_DIE2"},	// S_TROO_DIE1
    {"S_TROO_DIE2","SPR_TROO","A_Scream","S_TROO_DIE3"},	// S_TROO_DIE2
    {"S_TROO_DIE3","SPR_TROO","NULL","S_TROO_DIE4"},	// S_TROO_DIE3
    {"S_TROO_DIE4","SPR_TROO","A_Fall","S_TROO_DIE5"},	// S_TROO_DIE4
    {"S_TROO_DIE5","SPR_TROO","NULL","S_NULL"},	// S_TROO_DIE5
    {"S_TROO_XDIE1","SPR_TROO","NULL","S_TROO_XDIE2"},	// S_TROO_XDIE1
    {"S_TROO_XDIE2","SPR_TROO","A_XScream","S_TROO_XDIE3"},	// S_TROO_XDIE2
    {"S_TROO_XDIE3","SPR_TROO","NULL","S_TROO_XDIE4"},	// S_TROO_XDIE3
    {"S_TROO_XDIE4","SPR_TROO","A_Fall","S_TROO_XDIE5"},	// S_TROO_XDIE4
    {"S_TROO_XDIE5","SPR_TROO","NULL","S_TROO_XDIE6"},	// S_TROO_XDIE5
    {"S_TROO_XDIE6","SPR_TROO","NULL","S_TROO_XDIE7"},	// S_TROO_XDIE6
    {"S_TROO_XDIE7","SPR_TROO","NULL","S_TROO_XDIE8"},	// S_TROO_XDIE7
    {"S_TROO_XDIE8","SPR_TROO","NULL","S_NULL"},	// S_TROO_XDIE8
    {"S_TROO_RAISE1","SPR_TROO","NULL","S_TROO_RAISE2"},	// S_TROO_RAISE1
    {"S_TROO_RAISE2","SPR_TROO","NULL","S_TROO_RAISE3"},	// S_TROO_RAISE2
    {"S_TROO_RAISE3","SPR_TROO","NULL","S_TROO_RAISE4"},	// S_TROO_RAISE3
    {"S_TROO_RAISE4","SPR_TROO","NULL","S_TROO_RAISE5"},	// S_TROO_RAISE4
    {"S_TROO_RAISE5","SPR_TROO","NULL","S_TROO_RUN1"},	// S_TROO_RAISE5
    {"S_SARG_STND","SPR_SARG","A_Look","S_SARG_STND2"},	// S_SARG_STND
    {"S_SARG_STND2","SPR_SARG","A_Look","S_SARG_STND"},	// S_SARG_STND2
    {"S_SARG_RUN1","SPR_SARG","A_Chase","S_SARG_RUN2"},	// S_SARG_RUN1
    {"S_SARG_RUN2","SPR_SARG","A_Chase","S_SARG_RUN3"},	// S_SARG_RUN2
    {"S_SARG_RUN3","SPR_SARG","A_Chase","S_SARG_RUN4"},	// S_SARG_RUN3
    {"S_SARG_RUN4","SPR_SARG","A_Chase","S_SARG_RUN5"},	// S_SARG_RUN4
    {"S_SARG_RUN5","SPR_SARG","A_Chase","S_SARG_RUN6"},	// S_SARG_RUN5
    {"S_SARG_RUN6","SPR_SARG","A_Chase","S_SARG_RUN7"},	// S_SARG_RUN6
    {"S_SARG_RUN7","SPR_SARG","A_Chase","S_SARG_RUN8"},	// S_SARG_RUN7
    {"S_SARG_RUN8","SPR_SARG","A_Chase","S_SARG_RUN1"},	// S_SARG_RUN8
    {"S_SARG_ATK1","SPR_SARG","A_FaceTarget","S_SARG_ATK2"},	// S_SARG_ATK1
    {"S_SARG_ATK2","SPR_SARG","A_FaceTarget","S_SARG_ATK3"},	// S_SARG_ATK2
    {"S_SARG_ATK3","SPR_SARG","A_SargAttack","S_SARG_RUN1"},	// S_SARG_ATK3
    {"S_SARG_PAIN","SPR_SARG","NULL","S_SARG_PAIN2"},	// S_SARG_PAIN
    {"S_SARG_PAIN2","SPR_SARG","A_Pain","S_SARG_RUN1"},	// S_SARG_PAIN2
    {"S_SARG_DIE1","SPR_SARG","NULL","S_SARG_DIE2"},	// S_SARG_DIE1
    {"S_SARG_DIE2","SPR_SARG","A_Scream","S_SARG_DIE3"},	// S_SARG_DIE2
    {"S_SARG_DIE3","SPR_SARG","NULL","S_SARG_DIE4"},	// S_SARG_DIE3
    {"S_SARG_DIE4","SPR_SARG","A_Fall","S_SARG_DIE5"},	// S_SARG_DIE4
    {"S_SARG_DIE5","SPR_SARG","NULL","S_SARG_DIE6"},	// S_SARG_DIE5
    {"S_SARG_DIE6","SPR_SARG","NULL","S_NULL"},	// S_SARG_DIE6
    {"S_SARG_RAISE1","SPR_SARG","NULL","S_SARG_RAISE2"},	// S_SARG_RAISE1
    {"S_SARG_RAISE2","SPR_SARG","NULL","S_SARG_RAISE3"},	// S_SARG_RAISE2
    {"S_SARG_RAISE3","SPR_SARG","NULL","S_SARG_RAISE4"},	// S_SARG_RAISE3
    {"S_SARG_RAISE4","SPR_SARG","NULL","S_SARG_RAISE5"},	// S_SARG_RAISE4
    {"S_SARG_RAISE5","SPR_SARG","NULL","S_SARG_RAISE6"},	// S_SARG_RAISE5
    {"S_SARG_RAISE6","SPR_SARG","NULL","S_SARG_RUN1"},	// S_SARG_RAISE6
    {"S_HEAD_STND","SPR_HEAD","A_Look","S_HEAD_STND"},	// S_HEAD_STND
    {"S_HEAD_RUN1","SPR_HEAD","A_Chase","S_HEAD_RUN1"},	// S_HEAD_RUN1
    {"S_HEAD_ATK1","SPR_HEAD","A_FaceTarget","S_HEAD_ATK2"},	// S_HEAD_ATK1
    {"S_HEAD_ATK2","SPR_HEAD","A_FaceTarget","S_HEAD_ATK3"},	// S_HEAD_ATK2
    {"S_HEAD_ATK3","SPR_HEAD","A_HeadAttack","S_HEAD_RUN1"},	// S_HEAD_ATK3
    {"S_HEAD_PAIN","SPR_HEAD","NULL","S_HEAD_PAIN2"},	// S_HEAD_PAIN
    {"S_HEAD_PAIN2","SPR_HEAD","A_Pain","S_HEAD_PAIN3"},	// S_HEAD_PAIN2
    {"S_HEAD_PAIN3","SPR_HEAD","NULL","S_HEAD_RUN1"},	// S_HEAD_PAIN3
    {"S_HEAD_DIE1","SPR_HEAD","NULL","S_HEAD_DIE2"},	// S_HEAD_DIE1
    {"S_HEAD_DIE2","SPR_HEAD","A_Scream","S_HEAD_DIE3"},	// S_HEAD_DIE2
    {"S_HEAD_DIE3","SPR_HEAD","NULL","S_HEAD_DIE4"},	// S_HEAD_DIE3
    {"S_HEAD_DIE4","SPR_HEAD","NULL","S_HEAD_DIE5"},	// S_HEAD_DIE4
    {"S_HEAD_DIE5","SPR_HEAD","A_Fall","S_HEAD_DIE6"},	// S_HEAD_DIE5
    {"S_HEAD_DIE6","SPR_HEAD","NULL","S_NULL"},	// S_HEAD_DIE6
    {"S_HEAD_RAISE1","SPR_HEAD","NULL","S_HEAD_RAISE2"},	// S_HEAD_RAISE1
    {"S_HEAD_RAISE2","SPR_HEAD","NULL","S_HEAD_RAISE3"},	// S_HEAD_RAISE2
    {"S_HEAD_RAISE3","SPR_HEAD","NULL","S_HEAD_RAISE4"},	// S_HEAD_RAISE3
    {"S_HEAD_RAISE4","SPR_HEAD","NULL","S_HEAD_RAISE5"},	// S_HEAD_RAISE4
    {"S_HEAD_RAISE5","SPR_HEAD","NULL","S_HEAD_RAISE6"},	// S_HEAD_RAISE5
    {"S_HEAD_RAISE6","SPR_HEAD","NULL","S_HEAD_RUN1"},	// S_HEAD_RAISE6
    {"S_BRBALL1","SPR_BAL7","NULL","S_BRBALL2"},	// S_BRBALL1
    {"S_BRBALL2","SPR_BAL7","NULL","S_BRBALL1"},	// S_BRBALL2
    {"S_BRBALLX1","SPR_BAL7","NULL","S_BRBALLX2"},	// S_BRBALLX1
    {"S_BRBALLX2","SPR_BAL7","NULL","S_BRBALLX3"},	// S_BRBALLX2
    {"S_BRBALLX3","SPR_BAL7","NULL","S_NULL"},	// S_BRBALLX3
    {"S_BOSS_STND","SPR_BOSS","A_Look","S_BOSS_STND2"},	// S_BOSS_STND
    {"S_BOSS_STND2","SPR_BOSS","A_Look","S_BOSS_STND"},	// S_BOSS_STND2
    {"S_BOSS_RUN1","SPR_BOSS","A_Chase","S_BOSS_RUN2"},	// S_BOSS_RUN1
    {"S_BOSS_RUN2","SPR_BOSS","A_Chase","S_BOSS_RUN3"},	// S_BOSS_RUN2
    {"S_BOSS_RUN3","SPR_BOSS","A_Chase","S_BOSS_RUN4"},	// S_BOSS_RUN3
    {"S_BOSS_RUN4","SPR_BOSS","A_Chase","S_BOSS_RUN5"},	// S_BOSS_RUN4
    {"S_BOSS_RUN5","SPR_BOSS","A_Chase","S_BOSS_RUN6"},	// S_BOSS_RUN5
    {"S_BOSS_RUN6","SPR_BOSS","A_Chase","S_BOSS_RUN7"},	// S_BOSS_RUN6
    {"S_BOSS_RUN7","SPR_BOSS","A_Chase","S_BOSS_RUN8"},	// S_BOSS_RUN7
    {"S_BOSS_RUN8","SPR_BOSS","A_Chase","S_BOSS_RUN1"},	// S_BOSS_RUN8
    {"S_BOSS_ATK1","SPR_BOSS","A_FaceTarget","S_BOSS_ATK2"},	// S_BOSS_ATK1
    {"S_BOSS_ATK2","SPR_BOSS","A_FaceTarget","S_BOSS_ATK3"},	// S_BOSS_ATK2
    {"S_BOSS_ATK3","SPR_BOSS","A_BruisAttack","S_BOSS_RUN1"},	// S_BOSS_ATK3
    {"S_BOSS_PAIN","SPR_BOSS","NULL","S_BOSS_PAIN2"},	// S_BOSS_PAIN
    {"S_BOSS_PAIN2","SPR_BOSS","A_Pain","S_BOSS_RUN1"},	// S_BOSS_PAIN2
    {"S_BOSS_DIE1","SPR_BOSS","NULL","S_BOSS_DIE2"},	// S_BOSS_DIE1
    {"S_BOSS_DIE2","SPR_BOSS","A_Scream","S_BOSS_DIE3"},	// S_BOSS_DIE2
    {"S_BOSS_DIE3","SPR_BOSS","NULL","S_BOSS_DIE4"},	// S_BOSS_DIE3
    {"S_BOSS_DIE4","SPR_BOSS","A_Fall","S_BOSS_DIE5"},	// S_BOSS_DIE4
    {"S_BOSS_DIE5","SPR_BOSS","NULL","S_BOSS_DIE6"},	// S_BOSS_DIE5
    {"S_BOSS_DIE6","SPR_BOSS","NULL","S_BOSS_DIE7"},	// S_BOSS_DIE6
    {"S_BOSS_DIE7","SPR_BOSS","A_BossDeath","S_NULL"},	// S_BOSS_DIE7
    {"S_BOSS_RAISE1","SPR_BOSS","NULL","S_BOSS_RAISE2"},	// S_BOSS_RAISE1
    {"S_BOSS_RAISE2","SPR_BOSS","NULL","S_BOSS_RAISE3"},	// S_BOSS_RAISE2
    {"S_BOSS_RAISE3","SPR_BOSS","NULL","S_BOSS_RAISE4"},	// S_BOSS_RAISE3
    {"S_BOSS_RAISE4","SPR_BOSS","NULL","S_BOSS_RAISE5"},	// S_BOSS_RAISE4
    {"S_BOSS_RAISE5","SPR_BOSS","NULL","S_BOSS_RAISE6"},	// S_BOSS_RAISE5
    {"S_BOSS_RAISE6","SPR_BOSS","NULL","S_BOSS_RAISE7"},	// S_BOSS_RAISE6
    {"S_BOSS_RAISE7","SPR_BOSS","NULL","S_BOSS_RUN1"},	// S_BOSS_RAISE7
    {"S_BOS2_STND","SPR_BOS2","A_Look","S_BOS2_STND2"},	// S_BOS2_STND
    {"S_BOS2_STND2","SPR_BOS2","A_Look","S_BOS2_STND"},	// S_BOS2_STND2
    {"S_BOS2_RUN1","SPR_BOS2","A_Chase","S_BOS2_RUN2"},	// S_BOS2_RUN1
    {"S_BOS2_RUN2","SPR_BOS2","A_Chase","S_BOS2_RUN3"},	// S_BOS2_RUN2
    {"S_BOS2_RUN3","SPR_BOS2","A_Chase","S_BOS2_RUN4"},	// S_BOS2_RUN3
    {"S_BOS2_RUN4","SPR_BOS2","A_Chase","S_BOS2_RUN5"},	// S_BOS2_RUN4
    {"S_BOS2_RUN5","SPR_BOS2","A_Chase","S_BOS2_RUN6"},	// S_BOS2_RUN5
    {"S_BOS2_RUN6","SPR_BOS2","A_Chase","S_BOS2_RUN7"},	// S_BOS2_RUN6
    {"S_BOS2_RUN7","SPR_BOS2","A_Chase","S_BOS2_RUN8"},	// S_BOS2_RUN7
    {"S_BOS2_RUN8","SPR_BOS2","A_Chase","S_BOS2_RUN1"},	// S_BOS2_RUN8
    {"S_BOS2_ATK1","SPR_BOS2","A_FaceTarget","S_BOS2_ATK2"},	// S_BOS2_ATK1
    {"S_BOS2_ATK2","SPR_BOS2","A_FaceTarget","S_BOS2_ATK3"},	// S_BOS2_ATK2
    {"S_BOS2_ATK3","SPR_BOS2","A_BruisAttack","S_BOS2_RUN1"},	// S_BOS2_ATK3
    {"S_BOS2_PAIN","SPR_BOS2","NULL","S_BOS2_PAIN2"},	// S_BOS2_PAIN
    {"S_BOS2_PAIN2","SPR_BOS2","A_Pain","S_BOS2_RUN1"},	// S_BOS2_PAIN2
    {"S_BOS2_DIE1","SPR_BOS2","NULL","S_BOS2_DIE2"},	// S_BOS2_DIE1
    {"S_BOS2_DIE2","SPR_BOS2","A_Scream","S_BOS2_DIE3"},	// S_BOS2_DIE2
    {"S_BOS2_DIE3","SPR_BOS2","NULL","S_BOS2_DIE4"},	// S_BOS2_DIE3
    {"S_BOS2_DIE4","SPR_BOS2","A_Fall","S_BOS2_DIE5"},	// S_BOS2_DIE4
    {"S_BOS2_DIE5","SPR_BOS2","NULL","S_BOS2_DIE6"},	// S_BOS2_DIE5
    {"S_BOS2_DIE6","SPR_BOS2","NULL","S_BOS2_DIE7"},	// S_BOS2_DIE6
    {"S_BOS2_DIE7","SPR_BOS2","NULL","S_NULL"},	// S_BOS2_DIE7
    {"S_BOS2_RAISE1","SPR_BOS2","NULL","S_BOS2_RAISE2"},	// S_BOS2_RAISE1
    {"S_BOS2_RAISE2","SPR_BOS2","NULL","S_BOS2_RAISE3"},	// S_BOS2_RAISE2
    {"S_BOS2_RAISE3","SPR_BOS2","NULL","S_BOS2_RAISE4"},	// S_BOS2_RAISE3
    {"S_BOS2_RAISE4","SPR_BOS2","NULL","S_BOS2_RAISE5"},	// S_BOS2_RAISE4
    {"S_BOS2_RAISE5","SPR_BOS2","NULL","S_BOS2_RAISE6"},	// S_BOS2_RAISE5
    {"S_BOS2_RAISE6","SPR_BOS2","NULL","S_BOS2_RAISE7"},	// S_BOS2_RAISE6
    {"S_BOS2_RAISE7","SPR_BOS2","NULL","S_BOS2_RUN1"},	// S_BOS2_RAISE7
    {"S_SKULL_STND","SPR_SKUL","A_Look","S_SKULL_STND2"},	// S_SKULL_STND
    {"S_SKULL_STND2","SPR_SKUL","A_Look","S_SKULL_STND"},	// S_SKULL_STND2
    {"S_SKULL_RUN1","SPR_SKUL","A_Chase","S_SKULL_RUN2"},	// S_SKULL_RUN1
    {"S_SKULL_RUN2","SPR_SKUL","A_Chase","S_SKULL_RUN1"},	// S_SKULL_RUN2
    {"S_SKULL_ATK1","SPR_SKUL","A_FaceTarget","S_SKULL_ATK2"},	// S_SKULL_ATK1
    {"S_SKULL_ATK2","SPR_SKUL","A_SkullAttack","S_SKULL_ATK3"},	// S_SKULL_ATK2
    {"S_SKULL_ATK3","SPR_SKUL","NULL","S_SKULL_ATK4"},	// S_SKULL_ATK3
    {"S_SKULL_ATK4","SPR_SKUL","NULL","S_SKULL_ATK3"},	// S_SKULL_ATK4
    {"S_SKULL_PAIN","SPR_SKUL","NULL","S_SKULL_PAIN2"},	// S_SKULL_PAIN
    {"S_SKULL_PAIN2","SPR_SKUL","A_Pain","S_SKULL_RUN1"},	// S_SKULL_PAIN2
    {"S_SKULL_DIE1","SPR_SKUL","NULL","S_SKULL_DIE2"},	// S_SKULL_DIE1
    {"S_SKULL_DIE2","SPR_SKUL","A_Scream","S_SKULL_DIE3"},	// S_SKULL_DIE2
    {"S_SKULL_DIE3","SPR_SKUL","NULL","S_SKULL_DIE4"},	// S_SKULL_DIE3
    {"S_SKULL_DIE4","SPR_SKUL","A_Fall","S_SKULL_DIE5"},	// S_SKULL_DIE4
    {"S_SKULL_DIE5","SPR_SKUL","NULL","S_SKULL_DIE6"},	// S_SKULL_DIE5
    {"S_SKULL_DIE6","SPR_SKUL","NULL","S_NULL"},	// S_SKULL_DIE6
    {"S_SPID_STND","SPR_SPID","A_Look","S_SPID_STND2"},	// S_SPID_STND
    {"S_SPID_STND2","SPR_SPID","A_Look","S_SPID_STND"},	// S_SPID_STND2
    {"S_SPID_RUN1","SPR_SPID","A_Metal","S_SPID_RUN2"},	// S_SPID_RUN1
    {"S_SPID_RUN2","SPR_SPID","A_Chase","S_SPID_RUN3"},	// S_SPID_RUN2
    {"S_SPID_RUN3","SPR_SPID","A_Chase","S_SPID_RUN4"},	// S_SPID_RUN3
    {"S_SPID_RUN4","SPR_SPID","A_Chase","S_SPID_RUN5"},	// S_SPID_RUN4
    {"S_SPID_RUN5","SPR_SPID","A_Metal","S_SPID_RUN6"},	// S_SPID_RUN5
    {"S_SPID_RUN6","SPR_SPID","A_Chase","S_SPID_RUN7"},	// S_SPID_RUN6
    {"S_SPID_RUN7","SPR_SPID","A_Chase","S_SPID_RUN8"},	// S_SPID_RUN7
    {"S_SPID_RUN8","SPR_SPID","A_Chase","S_SPID_RUN9"},	// S_SPID_RUN8
    {"S_SPID_RUN9","SPR_SPID","A_Metal","S_SPID_RUN10"},	// S_SPID_RUN9
    {"S_SPID_RUN10","SPR_SPID","A_Chase","S_SPID_RUN11"},	// S_SPID_RUN10
    {"S_SPID_RUN11","SPR_SPID","A_Chase","S_SPID_RUN12"},	// S_SPID_RUN11
    {"S_SPID_RUN12","SPR_SPID","A_Chase","S_SPID_RUN1"},	// S_SPID_RUN12
    {"S_SPID_ATK1","SPR_SPID","A_FaceTarget","S_SPID_ATK2"},	// S_SPID_ATK1
    {"S_SPID_ATK2","SPR_SPID","A_SPosAttack","S_SPID_ATK3"},	// S_SPID_ATK2
    {"S_SPID_ATK3","SPR_SPID","A_SPosAttack","S_SPID_ATK4"},	// S_SPID_ATK3
    {"S_SPID_ATK4","SPR_SPID","A_SpidRefire","S_SPID_ATK2"},	// S_SPID_ATK4
    {"S_SPID_PAIN","SPR_SPID","NULL","S_SPID_PAIN2"},	// S_SPID_PAIN
    {"S_SPID_PAIN2","SPR_SPID","A_Pain","S_SPID_RUN1"},	// S_SPID_PAIN2
    {"S_SPID_DIE1","SPR_SPID","A_Scream","S_SPID_DIE2"},	// S_SPID_DIE1
    {"S_SPID_DIE2","SPR_SPID","A_Fall","S_SPID_DIE3"},	// S_SPID_DIE2
    {"S_SPID_DIE3","SPR_SPID","NULL","S_SPID_DIE4"},	// S_SPID_DIE3
    {"S_SPID_DIE4","SPR_SPID","NULL","S_SPID_DIE5"},	// S_SPID_DIE4
    {"S_SPID_DIE5","SPR_SPID","NULL","S_SPID_DIE6"},	// S_SPID_DIE5
    {"S_SPID_DIE6","SPR_SPID","NULL","S_SPID_DIE7"},	// S_SPID_DIE6
    {"S_SPID_DIE7","SPR_SPID","NULL","S_SPID_DIE8"},	// S_SPID_DIE7
    {"S_SPID_DIE8","SPR_SPID","NULL","S_SPID_DIE9"},	// S_SPID_DIE8
    {"S_SPID_DIE9","SPR_SPID","NULL","S_SPID_DIE10"},	// S_SPID_DIE9
    {"S_SPID_DIE10","SPR_SPID","NULL","S_SPID_DIE11"},	// S_SPID_DIE10
    {"S_SPID_DIE11","SPR_SPID","A_BossDeath","S_NULL"},	// S_SPID_DIE11
    {"S_BSPI_STND","SPR_BSPI","A_Look","S_BSPI_STND2"},	// S_BSPI_STND
    {"S_BSPI_STND2","SPR_BSPI","A_Look","S_BSPI_STND"},	// S_BSPI_STND2
    {"S_BSPI_SIGHT","SPR_BSPI","NULL","S_BSPI_RUN1"},	// S_BSPI_SIGHT
    {"S_BSPI_RUN1","SPR_BSPI","A_BabyMetal","S_BSPI_RUN2"},	// S_BSPI_RUN1
    {"S_BSPI_RUN2","SPR_BSPI","A_Chase","S_BSPI_RUN3"},	// S_BSPI_RUN2
    {"S_BSPI_RUN3","SPR_BSPI","A_Chase","S_BSPI_RUN4"},	// S_BSPI_RUN3
    {"S_BSPI_RUN4","SPR_BSPI","A_Chase","S_BSPI_RUN5"},	// S_BSPI_RUN4
    {"S_BSPI_RUN5","SPR_BSPI","A_Chase","S_BSPI_RUN6"},	// S_BSPI_RUN5
    {"S_BSPI_RUN6","SPR_BSPI","A_Chase","S_BSPI_RUN7"},	// S_BSPI_RUN6
    {"S_BSPI_RUN7","SPR_BSPI","A_BabyMetal","S_BSPI_RUN8"},	// S_BSPI_RUN7
    {"S_BSPI_RUN8","SPR_BSPI","A_Chase","S_BSPI_RUN9"},	// S_BSPI_RUN8
    {"S_BSPI_RUN9","SPR_BSPI","A_Chase","S_BSPI_RUN10"},	// S_BSPI_RUN9
    {"S_BSPI_RUN10","SPR_BSPI","A_Chase","S_BSPI_RUN11"},	// S_BSPI_RUN10
    {"S_BSPI_RUN11","SPR_BSPI","A_Chase","S_BSPI_RUN12"},	// S_BSPI_RUN11
    {"S_BSPI_RUN12","SPR_BSPI","A_Chase","S_BSPI_RUN1"},	// S_BSPI_RUN12
    {"S_BSPI_ATK1","SPR_BSPI","A_FaceTarget","S_BSPI_ATK2"},	// S_BSPI_ATK1
    {"S_BSPI_ATK2","SPR_BSPI","A_BspiAttack","S_BSPI_ATK3"},	// S_BSPI_ATK2
    {"S_BSPI_ATK3","SPR_BSPI","NULL","S_BSPI_ATK4"},	// S_BSPI_ATK3
    {"S_BSPI_ATK4","SPR_BSPI","A_SpidRefire","S_BSPI_ATK2"},	// S_BSPI_ATK4
    {"S_BSPI_PAIN","SPR_BSPI","NULL","S_BSPI_PAIN2"},	// S_BSPI_PAIN
    {"S_BSPI_PAIN2","SPR_BSPI","A_Pain","S_BSPI_RUN1"},	// S_BSPI_PAIN2
    {"S_BSPI_DIE1","SPR_BSPI","A_Scream","S_BSPI_DIE2"},	// S_BSPI_DIE1
    {"S_BSPI_DIE2","SPR_BSPI","A_Fall","S_BSPI_DIE3"},	// S_BSPI_DIE2
    {"S_BSPI_DIE3","SPR_BSPI","NULL","S_BSPI_DIE4"},	// S_BSPI_DIE3
    {"S_BSPI_DIE4","SPR_BSPI","NULL","S_BSPI_DIE5"},	// S_BSPI_DIE4
    {"S_BSPI_DIE5","SPR_BSPI","NULL","S_BSPI_DIE6"},	// S_BSPI_DIE5
    {"S_BSPI_DIE6","SPR_BSPI","NULL","S_BSPI_DIE7"},	// S_BSPI_DIE6
    {"S_BSPI_DIE7","SPR_BSPI","A_BossDeath","S_NULL"},	// S_BSPI_DIE7
    {"S_BSPI_RAISE1","SPR_BSPI","NULL","S_BSPI_RAISE2"},	// S_BSPI_RAISE1
    {"S_BSPI_RAISE2","SPR_BSPI","NULL","S_BSPI_RAISE3"},	// S_BSPI_RAISE2
    {"S_BSPI_RAISE3","SPR_BSPI","NULL","S_BSPI_RAISE4"},	// S_BSPI_RAISE3
    {"S_BSPI_RAISE4","SPR_BSPI","NULL","S_BSPI_RAISE5"},	// S_BSPI_RAISE4
    {"S_BSPI_RAISE5","SPR_BSPI","NULL","S_BSPI_RAISE6"},	// S_BSPI_RAISE5
    {"S_BSPI_RAISE6","SPR_BSPI","NULL","S_BSPI_RAISE7"},	// S_BSPI_RAISE6
    {"S_BSPI_RAISE7","SPR_BSPI","NULL","S_BSPI_RUN1"},	// S_BSPI_RAISE7
    {"S_ARACH_PLAZ","SPR_APLS","NULL","S_ARACH_PLAZ2"},	// S_ARACH_PLAZ
    {"S_ARACH_PLAZ2","SPR_APLS","NULL","S_ARACH_PLAZ"},	// S_ARACH_PLAZ2
    {"S_ARACH_PLEX","SPR_APBX","NULL","S_ARACH_PLEX2"},	// S_ARACH_PLEX
    {"S_ARACH_PLEX2","SPR_APBX","NULL","S_ARACH_PLEX3"},	// S_ARACH_PLEX2
    {"S_ARACH_PLEX3","SPR_APBX","NULL","S_ARACH_PLEX4"},	// S_ARACH_PLEX3
    {"S_ARACH_PLEX4","SPR_APBX","NULL","S_ARACH_PLEX5"},	// S_ARACH_PLEX4
    {"S_ARACH_PLEX5","SPR_APBX","NULL","S_NULL"},	// S_ARACH_PLEX5
    {"S_CYBER_STND","SPR_CYBR","A_Look","S_CYBER_STND2"},	// S_CYBER_STND
    {"S_CYBER_STND2","SPR_CYBR","A_Look","S_CYBER_STND"},	// S_CYBER_STND2
    {"S_CYBER_RUN1","SPR_CYBR","A_Hoof","S_CYBER_RUN2"},	// S_CYBER_RUN1
    {"S_CYBER_RUN2","SPR_CYBR","A_Chase","S_CYBER_RUN3"},	// S_CYBER_RUN2
    {"S_CYBER_RUN3","SPR_CYBR","A_Chase","S_CYBER_RUN4"},	// S_CYBER_RUN3
    {"S_CYBER_RUN4","SPR_CYBR","A_Chase","S_CYBER_RUN5"},	// S_CYBER_RUN4
    {"S_CYBER_RUN5","SPR_CYBR","A_Chase","S_CYBER_RUN6"},	// S_CYBER_RUN5
    {"S_CYBER_RUN6","SPR_CYBR","A_Chase","S_CYBER_RUN7"},	// S_CYBER_RUN6
    {"S_CYBER_RUN7","SPR_CYBR","A_Metal","S_CYBER_RUN8"},	// S_CYBER_RUN7
    {"S_CYBER_RUN8","SPR_CYBR","A_Chase","S_CYBER_RUN1"},	// S_CYBER_RUN8
    {"S_CYBER_ATK1","SPR_CYBR","A_FaceTarget","S_CYBER_ATK2"},	// S_CYBER_ATK1
    {"S_CYBER_ATK2","SPR_CYBR","A_CyberAttack","S_CYBER_ATK3"},	// S_CYBER_ATK2
    {"S_CYBER_ATK3","SPR_CYBR","A_FaceTarget","S_CYBER_ATK4"},	// S_CYBER_ATK3
    {"S_CYBER_ATK4","SPR_CYBR","A_CyberAttack","S_CYBER_ATK5"},	// S_CYBER_ATK4
    {"S_CYBER_ATK5","SPR_CYBR","A_FaceTarget","S_CYBER_ATK6"},	// S_CYBER_ATK5
    {"S_CYBER_ATK6","SPR_CYBR","A_CyberAttack","S_CYBER_RUN1"},	// S_CYBER_ATK6
    {"S_CYBER_PAIN","SPR_CYBR","A_Pain","S_CYBER_RUN1"},	// S_CYBER_PAIN
    {"S_CYBER_DIE1","SPR_CYBR","NULL","S_CYBER_DIE2"},	// S_CYBER_DIE1
    {"S_CYBER_DIE2","SPR_CYBR","A_Scream","S_CYBER_DIE3"},	// S_CYBER_DIE2
    {"S_CYBER_DIE3","SPR_CYBR","NULL","S_CYBER_DIE4"},	// S_CYBER_DIE3
    {"S_CYBER_DIE4","SPR_CYBR","NULL","S_CYBER_DIE5"},	// S_CYBER_DIE4
    {"S_CYBER_DIE5","SPR_CYBR","NULL","S_CYBER_DIE6"},	// S_CYBER_DIE5
    {"S_CYBER_DIE6","SPR_CYBR","A_Fall","S_CYBER_DIE7"},	// S_CYBER_DIE6
    {"S_CYBER_DIE7","SPR_CYBR","NULL","S_CYBER_DIE8"},	// S_CYBER_DIE7
    {"S_CYBER_DIE8","SPR_CYBR","NULL","S_CYBER_DIE9"},	// S_CYBER_DIE8
    {"S_CYBER_DIE9","SPR_CYBR","NULL","S_CYBER_DIE10"},	// S_CYBER_DIE9
    {"S_CYBER_DIE10","SPR_CYBR","A_BossDeath","S_NULL"},	// S_CYBER_DIE10
    {"S_PAIN_STND","SPR_PAIN","A_Look","S_PAIN_STND"},	// S_PAIN_STND
    {"S_PAIN_RUN1","SPR_PAIN","A_Chase","S_PAIN_RUN2"},	// S_PAIN_RUN1
    {"S_PAIN_RUN2","SPR_PAIN","A_Chase","S_PAIN_RUN3"},	// S_PAIN_RUN2
    {"S_PAIN_RUN3","SPR_PAIN","A_Chase","S_PAIN_RUN4"},	// S_PAIN_RUN3
    {"S_PAIN_RUN4","SPR_PAIN","A_Chase","S_PAIN_RUN5"},	// S_PAIN_RUN4
    {"S_PAIN_RUN5","SPR_PAIN","A_Chase","S_PAIN_RUN6"},	// S_PAIN_RUN5
    {"S_PAIN_RUN6","SPR_PAIN","A_Chase","S_PAIN_RUN1"},	// S_PAIN_RUN6
    {"S_PAIN_ATK1","SPR_PAIN","A_FaceTarget","S_PAIN_ATK2"},	// S_PAIN_ATK1
    {"S_PAIN_ATK2","SPR_PAIN","A_FaceTarget","S_PAIN_ATK3"},	// S_PAIN_ATK2
    {"S_PAIN_ATK3","SPR_PAIN","A_FaceTarget","S_PAIN_ATK4"},	// S_PAIN_ATK3
    {"S_PAIN_ATK4","SPR_PAIN","A_PainAttack","S_PAIN_RUN1"},	// S_PAIN_ATK4
    {"S_PAIN_PAIN","SPR_PAIN","NULL","S_PAIN_PAIN2"},	// S_PAIN_PAIN
    {"S_PAIN_PAIN2","SPR_PAIN","A_Pain","S_PAIN_RUN1"},	// S_PAIN_PAIN2
    {"S_PAIN_DIE1","SPR_PAIN","NULL","S_PAIN_DIE2"},	// S_PAIN_DIE1
    {"S_PAIN_DIE2","SPR_PAIN","A_Scream","S_PAIN_DIE3"},	// S_PAIN_DIE2
    {"S_PAIN_DIE3","SPR_PAIN","NULL","S_PAIN_DIE4"},	// S_PAIN_DIE3
    {"S_PAIN_DIE4","SPR_PAIN","NULL","S_PAIN_DIE5"},	// S_PAIN_DIE4
    {"S_PAIN_DIE5","SPR_PAIN","A_PainDie","S_PAIN_DIE6"},	// S_PAIN_DIE5
    {"S_PAIN_DIE6","SPR_PAIN","NULL","S_NULL"},	// S_PAIN_DIE6
    {"S_PAIN_RAISE1","SPR_PAIN","NULL","S_PAIN_RAISE2"},	// S_PAIN_RAISE1
    {"S_PAIN_RAISE2","SPR_PAIN","NULL","S_PAIN_RAISE3"},	// S_PAIN_RAISE2
    {"S_PAIN_RAISE3","SPR_PAIN","NULL","S_PAIN_RAISE4"},	// S_PAIN_RAISE3
    {"S_PAIN_RAISE4","SPR_PAIN","NULL","S_PAIN_RAISE5"},	// S_PAIN_RAISE4
    {"S_PAIN_RAISE5","SPR_PAIN","NULL","S_PAIN_RAISE6"},	// S_PAIN_RAISE5
    {"S_PAIN_RAISE6","SPR_PAIN","NULL","S_PAIN_RUN1"},	// S_PAIN_RAISE6
    {"S_SSWV_STND","SPR_SSWV","A_Look","S_SSWV_STND2"},	// S_SSWV_STND
    {"S_SSWV_STND2","SPR_SSWV","A_Look","S_SSWV_STND"},	// S_SSWV_STND2
    {"S_SSWV_RUN1","SPR_SSWV","A_Chase","S_SSWV_RUN2"},	// S_SSWV_RUN1
    {"S_SSWV_RUN2","SPR_SSWV","A_Chase","S_SSWV_RUN3"},	// S_SSWV_RUN2
    {"S_SSWV_RUN3","SPR_SSWV","A_Chase","S_SSWV_RUN4"},	// S_SSWV_RUN3
    {"S_SSWV_RUN4","SPR_SSWV","A_Chase","S_SSWV_RUN5"},	// S_SSWV_RUN4
    {"S_SSWV_RUN5","SPR_SSWV","A_Chase","S_SSWV_RUN6"},	// S_SSWV_RUN5
    {"S_SSWV_RUN6","SPR_SSWV","A_Chase","S_SSWV_RUN7"},	// S_SSWV_RUN6
    {"S_SSWV_RUN7","SPR_SSWV","A_Chase","S_SSWV_RUN8"},	// S_SSWV_RUN7
    {"S_SSWV_RUN8","SPR_SSWV","A_Chase","S_SSWV_RUN1"},	// S_SSWV_RUN8
    {"S_SSWV_ATK1","SPR_SSWV","A_FaceTarget","S_SSWV_ATK2"},	// S_SSWV_ATK1
    {"S_SSWV_ATK2","SPR_SSWV","A_FaceTarget","S_SSWV_ATK3"},	// S_SSWV_ATK2
    {"S_SSWV_ATK3","SPR_SSWV","A_CPosAttack","S_SSWV_ATK4"},	// S_SSWV_ATK3
    {"S_SSWV_ATK4","SPR_SSWV","A_FaceTarget","S_SSWV_ATK5"},	// S_SSWV_ATK4
    {"S_SSWV_ATK5","SPR_SSWV","A_CPosAttack","S_SSWV_ATK6"},	// S_SSWV_ATK5
    {"S_SSWV_ATK6","SPR_SSWV","A_CPosRefire","S_SSWV_ATK2"},	// S_SSWV_ATK6
    {"S_SSWV_PAIN","SPR_SSWV","NULL","S_SSWV_PAIN2"},	// S_SSWV_PAIN
    {"S_SSWV_PAIN2","SPR_SSWV","A_Pain","S_SSWV_RUN1"},	// S_SSWV_PAIN2
    {"S_SSWV_DIE1","SPR_SSWV","NULL","S_SSWV_DIE2"},	// S_SSWV_DIE1
    {"S_SSWV_DIE2","SPR_SSWV","A_Scream","S_SSWV_DIE3"},	// S_SSWV_DIE2
    {"S_SSWV_DIE3","SPR_SSWV","A_Fall","S_SSWV_DIE4"},	// S_SSWV_DIE3
    {"S_SSWV_DIE4","SPR_SSWV","NULL","S_SSWV_DIE5"},	// S_SSWV_DIE4
    {"S_SSWV_DIE5","SPR_SSWV","NULL","S_NULL"},	// S_SSWV_DIE5
    {"S_SSWV_XDIE1","SPR_SSWV","NULL","S_SSWV_XDIE2"},	// S_SSWV_XDIE1
    {"S_SSWV_XDIE2","SPR_SSWV","A_XScream","S_SSWV_XDIE3"},	// S_SSWV_XDIE2
    {"S_SSWV_XDIE3","SPR_SSWV","A_Fall","S_SSWV_XDIE4"},	// S_SSWV_XDIE3
    {"S_SSWV_XDIE4","SPR_SSWV","NULL","S_SSWV_XDIE5"},	// S_SSWV_XDIE4
    {"S_SSWV_XDIE5","SPR_SSWV","NULL","S_SSWV_XDIE6"},	// S_SSWV_XDIE5
    {"S_SSWV_XDIE6","SPR_SSWV","NULL","S_SSWV_XDIE7"},	// S_SSWV_XDIE6
    {"S_SSWV_XDIE7","SPR_SSWV","NULL","S_SSWV_XDIE8"},	// S_SSWV_XDIE7
    {"S_SSWV_XDIE8","SPR_SSWV","NULL","S_SSWV_XDIE9"},	// S_SSWV_XDIE8
    {"S_SSWV_XDIE9","SPR_SSWV","NULL","S_NULL"},	// S_SSWV_XDIE9
    {"S_SSWV_RAISE1","SPR_SSWV","NULL","S_SSWV_RAISE2"},	// S_SSWV_RAISE1
    {"S_SSWV_RAISE2","SPR_SSWV","NULL","S_SSWV_RAISE3"},	// S_SSWV_RAISE2
    {"S_SSWV_RAISE3","SPR_SSWV","NULL","S_SSWV_RAISE4"},	// S_SSWV_RAISE3
    {"S_SSWV_RAISE4","SPR_SSWV","NULL","S_SSWV_RAISE5"},	// S_SSWV_RAISE4
    {"S_SSWV_RAISE5","SPR_SSWV","NULL","S_SSWV_RUN1"},	// S_SSWV_RAISE5
    {"S_KEENSTND","SPR_KEEN","NULL","S_KEENSTND"},	// S_KEENSTND
    {"S_COMMKEEN","SPR_KEEN","NULL","S_COMMKEEN2"},	// S_COMMKEEN
    {"S_COMMKEEN2","SPR_KEEN","NULL","S_COMMKEEN3"},	// S_COMMKEEN2
    {"S_COMMKEEN3","SPR_KEEN","A_Scream","S_COMMKEEN4"},	// S_COMMKEEN3
    {"S_COMMKEEN4","SPR_KEEN","NULL","S_COMMKEEN5"},	// S_COMMKEEN4
    {"S_COMMKEEN5","SPR_KEEN","NULL","S_COMMKEEN6"},	// S_COMMKEEN5
    {"S_COMMKEEN6","SPR_KEEN","NULL","S_COMMKEEN7"},	// S_COMMKEEN6
    {"S_COMMKEEN7","SPR_KEEN","NULL","S_COMMKEEN8"},	// S_COMMKEEN7
    {"S_COMMKEEN8","SPR_KEEN","NULL","S_COMMKEEN9"},	// S_COMMKEEN8
    {"S_COMMKEEN9","SPR_KEEN","NULL","S_COMMKEEN10"},	// S_COMMKEEN9
    {"S_COMMKEEN10","SPR_KEEN","NULL","S_COMMKEEN11"},	// S_COMMKEEN10
    {"S_COMMKEEN11","SPR_KEEN","A_KeenDie","S_COMMKEEN12"},// S_COMMKEEN11
    {"S_COMMKEEN12","SPR_KEEN","NULL","S_NULL"},		// S_COMMKEEN12
    {"S_KEENPAIN","SPR_KEEN","NULL","S_KEENPAIN2"},	// S_KEENPAIN
    {"S_KEENPAIN2","SPR_KEEN","A_Pain","S_KEENSTND"},	// S_KEENPAIN2
    {"S_BRAIN","SPR_BBRN","NULL","S_NULL"},		// S_BRAIN
    {"S_BRAIN_PAIN","SPR_BBRN","A_BrainPain","S_BRAIN"},	// S_BRAIN_PAIN
    {"S_BRAIN_DIE1","SPR_BBRN","A_BrainScream","S_BRAIN_DIE2"},	// S_BRAIN_DIE1
    {"S_BRAIN_DIE2","SPR_BBRN","NULL","S_BRAIN_DIE3"},	// S_BRAIN_DIE2
    {"S_BRAIN_DIE3","SPR_BBRN","NULL","S_BRAIN_DIE4"},	// S_BRAIN_DIE3
    {"S_BRAIN_DIE4","SPR_BBRN","A_BrainDie","S_NULL"},	// S_BRAIN_DIE4
    {"S_BRAINEYE","SPR_SSWV","A_Look","S_BRAINEYE"},	// S_BRAINEYE
    {"S_BRAINEYESEE","SPR_SSWV","A_BrainAwake","S_BRAINEYE1"},	// S_BRAINEYESEE
    {"S_BRAINEYE1","SPR_SSWV","A_BrainSpit","S_BRAINEYE1"},	// S_BRAINEYE1
    {"S_SPAWN1","SPR_BOSF","A_SpawnSound","S_SPAWN2"},	// S_SPAWN1
    {"S_SPAWN2","SPR_BOSF","A_SpawnFly","S_SPAWN3"},	// S_SPAWN2
    {"S_SPAWN3","SPR_BOSF","A_SpawnFly","S_SPAWN4"},	// S_SPAWN3
    {"S_SPAWN4","SPR_BOSF","A_SpawnFly","S_SPAWN1"},	// S_SPAWN4
    {"S_SPAWNFIRE1","SPR_FIRE","A_Fire","S_SPAWNFIRE2"},	// S_SPAWNFIRE1
    {"S_SPAWNFIRE2","SPR_FIRE","A_Fire","S_SPAWNFIRE3"},	// S_SPAWNFIRE2
    {"S_SPAWNFIRE3","SPR_FIRE","A_Fire","S_SPAWNFIRE4"},	// S_SPAWNFIRE3
    {"S_SPAWNFIRE4","SPR_FIRE","A_Fire","S_SPAWNFIRE5"},	// S_SPAWNFIRE4
    {"S_SPAWNFIRE5","SPR_FIRE","A_Fire","S_SPAWNFIRE6"},	// S_SPAWNFIRE5
    {"S_SPAWNFIRE6","SPR_FIRE","A_Fire","S_SPAWNFIRE7"},	// S_SPAWNFIRE6
    {"S_SPAWNFIRE7","SPR_FIRE","A_Fire","S_SPAWNFIRE8"},	// S_SPAWNFIRE7
    {"S_SPAWNFIRE8","SPR_FIRE","A_Fire","S_NULL"},		// S_SPAWNFIRE8
    {"S_BRAINEXPLODE1","SPR_MISL","NULL","S_BRAINEXPLODE2"},	// S_BRAINEXPLODE1
    {"S_BRAINEXPLODE2","SPR_MISL","NULL","S_BRAINEXPLODE3"},	// S_BRAINEXPLODE2
    {"S_BRAINEXPLODE3","SPR_MISL","A_BrainExplode","S_NULL"},	// S_BRAINEXPLODE3
    {"S_ARM1","SPR_ARM1","NULL","S_ARM1A"},	// S_ARM1
    {"S_ARM1A","SPR_ARM1","NULL","S_ARM1"},	// S_ARM1A
    {"S_ARM2","SPR_ARM2","NULL","S_ARM2A"},	// S_ARM2
    {"S_ARM2A","SPR_ARM2","NULL","S_ARM2"},	// S_ARM2A
    {"S_BAR1","SPR_BAR1","NULL","S_BAR2"},	// S_BAR1
    {"S_BAR2","SPR_BAR1","NULL","S_BAR1"},	// S_BAR2
    {"S_BEXP","SPR_BEXP","NULL","S_BEXP2"},	// S_BEXP
    {"S_BEXP2","SPR_BEXP","A_Scream","S_BEXP3"},	// S_BEXP2
    {"S_BEXP3","SPR_BEXP","NULL","S_BEXP4"},	// S_BEXP3
    {"S_BEXP4","SPR_BEXP","A_Explode","S_BEXP5"},	// S_BEXP4
    {"S_BEXP5","SPR_BEXP","NULL","S_NULL"},	// S_BEXP5
    {"S_BBAR1","SPR_FCAN","NULL","S_BBAR2"},	// S_BBAR1
    {"S_BBAR2","SPR_FCAN","NULL","S_BBAR3"},	// S_BBAR2
    {"S_BBAR3","SPR_FCAN","NULL","S_BBAR1"},	// S_BBAR3
    {"S_BON1","SPR_BON1","NULL","S_BON1A"},	// S_BON1
    {"S_BON1A","SPR_BON1","NULL","S_BON1B"},	// S_BON1A
    {"S_BON1B","SPR_BON1","NULL","S_BON1C"},	// S_BON1B
    {"S_BON1C","SPR_BON1","NULL","S_BON1D"},	// S_BON1C
    {"S_BON1D","SPR_BON1","NULL","S_BON1E"},	// S_BON1D
    {"S_BON1E","SPR_BON1","NULL","S_BON1"},	// S_BON1E
    {"S_BON2","SPR_BON2","NULL","S_BON2A"},	// S_BON2
    {"S_BON2A","SPR_BON2","NULL","S_BON2B"},	// S_BON2A
    {"S_BON2B","SPR_BON2","NULL","S_BON2C"},	// S_BON2B
    {"S_BON2C","SPR_BON2","NULL","S_BON2D"},	// S_BON2C
    {"S_BON2D","SPR_BON2","NULL","S_BON2E"},	// S_BON2D
    {"S_BON2E","SPR_BON2","NULL","S_BON2"},	// S_BON2E
    {"S_BKEY","SPR_BKEY","NULL","S_BKEY2"},	// S_BKEY
    {"S_BKEY2","SPR_BKEY","NULL","S_BKEY"},	// S_BKEY2
    {"S_RKEY","SPR_RKEY","NULL","S_RKEY2"},	// S_RKEY
    {"S_RKEY2","SPR_RKEY","NULL","S_RKEY"},	// S_RKEY2
    {"S_YKEY","SPR_YKEY","NULL","S_YKEY2"},	// S_YKEY
    {"S_YKEY2","SPR_YKEY","NULL","S_YKEY"},	// S_YKEY2
    {"S_BSKULL","SPR_BSKU","NULL","S_BSKULL2"},	// S_BSKULL
    {"S_BSKULL2","SPR_BSKU","NULL","S_BSKULL"},	// S_BSKULL2
    {"S_RSKULL","SPR_RSKU","NULL","S_RSKULL2"},	// S_RSKULL
    {"S_RSKULL2","SPR_RSKU","NULL","S_RSKULL"},	// S_RSKULL2
    {"S_YSKULL","SPR_YSKU","NULL","S_YSKULL2"},	// S_YSKULL
    {"S_YSKULL2","SPR_YSKU","NULL","S_YSKULL"},	// S_YSKULL2
    {"S_STIM","SPR_STIM","NULL","S_NULL"},	// S_STIM
    {"S_MEDI","SPR_MEDI","NULL","S_NULL"},	// S_MEDI
    {"S_SOUL","SPR_SOUL","NULL","S_SOUL2"},	// S_SOUL
    {"S_SOUL2","SPR_SOUL","NULL","S_SOUL3"},	// S_SOUL2
    {"S_SOUL3","SPR_SOUL","NULL","S_SOUL4"},	// S_SOUL3
    {"S_SOUL4","SPR_SOUL","NULL","S_SOUL5"},	// S_SOUL4
    {"S_SOUL5","SPR_SOUL","NULL","S_SOUL6"},	// S_SOUL5
    {"S_SOUL6","SPR_SOUL","NULL","S_SOUL"},	// S_SOUL6
    {"S_PINV","SPR_PINV","NULL","S_PINV2"},	// S_PINV
    {"S_PINV2","SPR_PINV","NULL","S_PINV3"},	// S_PINV2
    {"S_PINV3","SPR_PINV","NULL","S_PINV4"},	// S_PINV3
    {"S_PINV4","SPR_PINV","NULL","S_PINV"},	// S_PINV4
    {"S_PSTR","SPR_PSTR","NULL","S_NULL"},	// S_PSTR
    {"S_PINS","SPR_PINS","NULL","S_PINS2"},	// S_PINS
    {"S_PINS2","SPR_PINS","NULL","S_PINS3"},	// S_PINS2
    {"S_PINS3","SPR_PINS","NULL","S_PINS4"},	// S_PINS3
    {"S_PINS4","SPR_PINS","NULL","S_PINS"},	// S_PINS4
    {"S_MEGA","SPR_MEGA","NULL","S_MEGA2"},	// S_MEGA
    {"S_MEGA2","SPR_MEGA","NULL","S_MEGA3"},	// S_MEGA2
    {"S_MEGA3","SPR_MEGA","NULL","S_MEGA4"},	// S_MEGA3
    {"S_MEGA4","SPR_MEGA","NULL","S_MEGA"},	// S_MEGA4
    {"S_SUIT","SPR_SUIT","NULL","S_NULL"},	// S_SUIT
    {"S_PMAP","SPR_PMAP","NULL","S_PMAP2"},	// S_PMAP
    {"S_PMAP2","SPR_PMAP","NULL","S_PMAP3"},	// S_PMAP2
    {"S_PMAP3","SPR_PMAP","NULL","S_PMAP4"},	// S_PMAP3
    {"S_PMAP4","SPR_PMAP","NULL","S_PMAP5"},	// S_PMAP4
    {"S_PMAP5","SPR_PMAP","NULL","S_PMAP6"},	// S_PMAP5
    {"S_PMAP6","SPR_PMAP","NULL","S_PMAP"},	// S_PMAP6
    {"S_PVIS","SPR_PVIS","NULL","S_PVIS2"},	// S_PVIS
    {"S_PVIS2","SPR_PVIS","NULL","S_PVIS"},	// S_PVIS2
    {"S_CLIP","SPR_CLIP","NULL","S_NULL"},	// S_CLIP
    {"S_AMMO","SPR_AMMO","NULL","S_NULL"},	// S_AMMO
    {"S_ROCK","SPR_ROCK","NULL","S_NULL"},	// S_ROCK
    {"S_BROK","SPR_BROK","NULL","S_NULL"},	// S_BROK
    {"S_CELL","SPR_CELL","NULL","S_NULL"},	// S_CELL
    {"S_CELP","SPR_CELP","NULL","S_NULL"},	// S_CELP
    {"S_SHEL","SPR_SHEL","NULL","S_NULL"},	// S_SHEL
    {"S_SBOX","SPR_SBOX","NULL","S_NULL"},	// S_SBOX
    {"S_BPAK","SPR_BPAK","NULL","S_NULL"},	// S_BPAK
    {"S_BFUG","SPR_BFUG","NULL","S_NULL"},	// S_BFUG
    {"S_MGUN","SPR_MGUN","NULL","S_NULL"},	// S_MGUN
    {"S_CSAW","SPR_CSAW","NULL","S_NULL"},	// S_CSAW
    {"S_LAUN","SPR_LAUN","NULL","S_NULL"},	// S_LAUN
    {"S_PLAS","SPR_PLAS","NULL","S_NULL"},	// S_PLAS
    {"S_SHOT","SPR_SHOT","NULL","S_NULL"},	// S_SHOT
    {"S_SHOT2","SPR_SGN2","NULL","S_NULL"},	// S_SHOT2
    {"S_COLU","SPR_COLU","NULL","S_NULL"},	// S_COLU
    {"S_STALAG","SPR_SMT2","NULL","S_NULL"},	// S_STALAG
    {"S_BLOODYTWITCH","SPR_GOR1","NULL","S_BLOODYTWITCH2"},	// S_BLOODYTWITCH
    {"S_BLOODYTWITCH2","SPR_GOR1","NULL","S_BLOODYTWITCH3"},	// S_BLOODYTWITCH2
    {"S_BLOODYTWITCH3","SPR_GOR1","NULL","S_BLOODYTWITCH4"},	// S_BLOODYTWITCH3
    {"S_BLOODYTWITCH4","SPR_GOR1","NULL","S_BLOODYTWITCH"},	// S_BLOODYTWITCH4
    {"S_DEADTORSO","SPR_PLAY","NULL","S_NULL"},	// S_DEADTORSO
    {"S_DEADBOTTOM","SPR_PLAY","NULL","S_NULL"},	// S_DEADBOTTOM
    {"S_HEADSONSTICK","SPR_POL2","NULL","S_NULL"},	// S_HEADSONSTICK
    {"S_GIBS","SPR_POL5","NULL","S_NULL"},	// S_GIBS
    {"S_HEADONASTICK","SPR_POL4","NULL","S_NULL"},	// S_HEADONASTICK
    {"S_HEADCANDLES","SPR_POL3","NULL","S_HEADCANDLES2"},	// S_HEADCANDLES
    {"S_HEADCANDLES2","SPR_POL3","NULL","S_HEADCANDLES"},	// S_HEADCANDLES2
    {"S_DEADSTICK","SPR_POL1","NULL","S_NULL"},	// S_DEADSTICK
    {"S_LIVESTICK","SPR_POL6","NULL","S_LIVESTICK2"},	// S_LIVESTICK
    {"S_LIVESTICK2","SPR_POL6","NULL","S_LIVESTICK"},	// S_LIVESTICK2
    {"S_MEAT2","SPR_GOR2","NULL","S_NULL"},	// S_MEAT2
    {"S_MEAT3","SPR_GOR3","NULL","S_NULL"},	// S_MEAT3
    {"S_MEAT4","SPR_GOR4","NULL","S_NULL"},	// S_MEAT4
    {"S_MEAT5","SPR_GOR5","NULL","S_NULL"},	// S_MEAT5
    {"S_STALAGTITE","SPR_SMIT","NULL","S_NULL"},	// S_STALAGTITE
    {"S_TALLGRNCOL","SPR_COL1","NULL","S_NULL"},	// S_TALLGRNCOL
    {"S_SHRTGRNCOL","SPR_COL2","NULL","S_NULL"},	// S_SHRTGRNCOL
    {"S_TALLREDCOL","SPR_COL3","NULL","S_NULL"},	// S_TALLREDCOL
    {"S_SHRTREDCOL","SPR_COL4","NULL","S_NULL"},	// S_SHRTREDCOL
    {"S_CANDLESTIK","SPR_CAND","NULL","S_NULL"},	// S_CANDLESTIK
    {"S_CANDELABRA","SPR_CBRA","NULL","S_NULL"},	// S_CANDELABRA
    {"S_SKULLCOL","SPR_COL6","NULL","S_NULL"},	// S_SKULLCOL
    {"S_TORCHTREE","SPR_TRE1","NULL","S_NULL"},	// S_TORCHTREE
    {"S_BIGTREE","SPR_TRE2","NULL","S_NULL"},	// S_BIGTREE
    {"S_TECHPILLAR","SPR_ELEC","NULL","S_NULL"},	// S_TECHPILLAR
    {"S_EVILEYE","SPR_CEYE","NULL","S_EVILEYE2"},	// S_EVILEYE
    {"S_EVILEYE2","SPR_CEYE","NULL","S_EVILEYE3"},	// S_EVILEYE2
    {"S_EVILEYE3","SPR_CEYE","NULL","S_EVILEYE4"},	// S_EVILEYE3
    {"S_EVILEYE4","SPR_CEYE","NULL","S_EVILEYE"},	// S_EVILEYE4
    {"S_FLOATSKULL","SPR_FSKU","NULL","S_FLOATSKULL2"},	// S_FLOATSKULL
    {"S_FLOATSKULL2","SPR_FSKU","NULL","S_FLOATSKULL3"},	// S_FLOATSKULL2
    {"S_FLOATSKULL3","SPR_FSKU","NULL","S_FLOATSKULL"},	// S_FLOATSKULL3
    {"S_HEARTCOL","SPR_COL5","NULL","S_HEARTCOL2"},	// S_HEARTCOL
    {"S_HEARTCOL2","SPR_COL5","NULL","S_HEARTCOL"},	// S_HEARTCOL2
    {"S_BLUETORCH","SPR_TBLU","NULL","S_BLUETORCH2"},	// S_BLUETORCH
    {"S_BLUETORCH2","SPR_TBLU","NULL","S_BLUETORCH3"},	// S_BLUETORCH2
    {"S_BLUETORCH3","SPR_TBLU","NULL","S_BLUETORCH4"},	// S_BLUETORCH3
    {"S_BLUETORCH4","SPR_TBLU","NULL","S_BLUETORCH"},	// S_BLUETORCH4
    {"S_GREENTORCH","SPR_TGRN","NULL","S_GREENTORCH2"},	// S_GREENTORCH
    {"S_GREENTORCH2","SPR_TGRN","NULL","S_GREENTORCH3"},	// S_GREENTORCH2
    {"S_GREENTORCH3","SPR_TGRN","NULL","S_GREENTORCH4"},	// S_GREENTORCH3
    {"S_GREENTORCH4","SPR_TGRN","NULL","S_GREENTORCH"},	// S_GREENTORCH4
    {"S_REDTORCH","SPR_TRED","NULL","S_REDTORCH2"},	// S_REDTORCH
    {"S_REDTORCH2","SPR_TRED","NULL","S_REDTORCH3"},	// S_REDTORCH2
    {"S_REDTORCH3","SPR_TRED","NULL","S_REDTORCH4"},	// S_REDTORCH3
    {"S_REDTORCH4","SPR_TRED","NULL","S_REDTORCH"},	// S_REDTORCH4
    {"S_BTORCHSHRT","SPR_SMBT","NULL","S_BTORCHSHRT2"},	// S_BTORCHSHRT
    {"S_BTORCHSHRT2","SPR_SMBT","NULL","S_BTORCHSHRT3"},	// S_BTORCHSHRT2
    {"S_BTORCHSHRT3","SPR_SMBT","NULL","S_BTORCHSHRT4"},	// S_BTORCHSHRT3
    {"S_BTORCHSHRT4","SPR_SMBT","NULL","S_BTORCHSHRT"},	// S_BTORCHSHRT4
    {"S_GTORCHSHRT","SPR_SMGT","NULL","S_GTORCHSHRT2"},	// S_GTORCHSHRT
    {"S_GTORCHSHRT2","SPR_SMGT","NULL","S_GTORCHSHRT3"},	// S_GTORCHSHRT2
    {"S_GTORCHSHRT3","SPR_SMGT","NULL","S_GTORCHSHRT4"},	// S_GTORCHSHRT3
    {"S_GTORCHSHRT4","SPR_SMGT","NULL","S_GTORCHSHRT"},	// S_GTORCHSHRT4
    {"S_RTORCHSHRT","SPR_SMRT","NULL","S_RTORCHSHRT2"},	// S_RTORCHSHRT
    {"S_RTORCHSHRT2","SPR_SMRT","NULL","S_RTORCHSHRT3"},	// S_RTORCHSHRT2
    {"S_RTORCHSHRT3","SPR_SMRT","NULL","S_RTORCHSHRT4"},	// S_RTORCHSHRT3
    {"S_RTORCHSHRT4","SPR_SMRT","NULL","S_RTORCHSHRT"},	// S_RTORCHSHRT4
    {"S_HANGNOGUTS","SPR_HDB1","NULL","S_NULL"},	// S_HANGNOGUTS
    {"S_HANGBNOBRAIN","SPR_HDB2","NULL","S_NULL"},	// S_HANGBNOBRAIN
    {"S_HANGTLOOKDN","SPR_HDB3","NULL","S_NULL"},	// S_HANGTLOOKDN
    {"S_HANGTSKULL","SPR_HDB4","NULL","S_NULL"},	// S_HANGTSKULL
    {"S_HANGTLOOKUP","SPR_HDB5","NULL","S_NULL"},	// S_HANGTLOOKUP
    {"S_HANGTNOBRAIN","SPR_HDB6","NULL","S_NULL"},	// S_HANGTNOBRAIN
    {"S_COLONGIBS","SPR_POB1","NULL","S_NULL"},	// S_COLONGIBS
    {"S_SMALLPOOL","SPR_POB2","NULL","S_NULL"},	// S_SMALLPOOL
    {"S_BRAINSTEM","SPR_BRS1","NULL","S_NULL"},		// S_BRAINSTEM
    {"S_TECHLAMP","SPR_TLMP","NULL","S_TECHLAMP2"},	// S_TECHLAMP
    {"S_TECHLAMP2","SPR_TLMP","NULL","S_TECHLAMP3"},	// S_TECHLAMP2
    {"S_TECHLAMP3","SPR_TLMP","NULL","S_TECHLAMP4"},	// S_TECHLAMP3
    {"S_TECHLAMP4","SPR_TLMP","NULL","S_TECHLAMP"},	// S_TECHLAMP4
    {"S_TECH2LAMP","SPR_TLP2","NULL","S_TECH2LAMP2"},	// S_TECH2LAMP
    {"S_TECH2LAMP2","SPR_TLP2","NULL","S_TECH2LAMP3"},	// S_TECH2LAMP2
    {"S_TECH2LAMP3","SPR_TLP2","NULL","S_TECH2LAMP4"},	// S_TECH2LAMP3
    {"S_TECH2LAMP4","SPR_TLP2","NULL","S_TECH2LAMP"}	// S_TECH2LAMP4
};
*/




boolean
P_SetMobjState
( mobj_t*	mobj,
  statenum_t	state )
{
    state_t*	st;

    do
    {
	if (state == S_NULL)
	{
	    mobj->state = (state_t *) S_NULL;
	    P_RemoveMobj (mobj);
	    return false;
	}

	st = &states[state];
	mobj->state = st;
	mobj->tics = st->tics;
	mobj->sprite = st->sprite;
	mobj->frame = st->frame;

	// Modified handling.
	// Call action functions when the state is set
	if (st->action.acp1)
    {
	    st->action.acp1(mobj);	
    }
	
	state = st->nextstate;
    } while (!mobj->tics);
				
    return true;
}


//
// P_ExplodeMissile  
//
void P_ExplodeMissile (mobj_t* mo)
{
    mo->momx = mo->momy = mo->momz = 0;

    P_SetMobjState (mo, mobjinfo[mo->type].deathstate);

    mo->tics -= P_Random()&3;

    if (mo->tics < 1)
	mo->tics = 1;

    mo->flags &= ~MF_MISSILE;

    if (mo->info->deathsound)
	S_StartSound (mo, mo->info->deathsound);
}


//
// P_XYMovement  
//
#define STOPSPEED		0x1000
#define FRICTION		0xe800

void P_XYMovement (mobj_t* mo) 
{ 	
    fixed_t 	ptryx;
    fixed_t	ptryy;
    player_t*	player;
    fixed_t	xmove;
    fixed_t	ymove;
			
    if (!mo->momx && !mo->momy)
    {
	if (mo->flags & MF_SKULLFLY)
	{
	    // the skull slammed into something
	    mo->flags &= ~MF_SKULLFLY;
	    mo->momx = mo->momy = mo->momz = 0;

	    P_SetMobjState (mo, mo->info->spawnstate);
	}
	return;
    }
	
    player = mo->player;
		
    if (mo->momx > MAXMOVE)
	mo->momx = MAXMOVE;
    else if (mo->momx < -MAXMOVE)
	mo->momx = -MAXMOVE;

    if (mo->momy > MAXMOVE)
	mo->momy = MAXMOVE;
    else if (mo->momy < -MAXMOVE)
	mo->momy = -MAXMOVE;
		
    xmove = mo->momx;
    ymove = mo->momy;
	
    do
    {
	if (xmove > MAXMOVE/2 || ymove > MAXMOVE/2)
	{
	    ptryx = mo->x + xmove/2;
	    ptryy = mo->y + ymove/2;
	    xmove >>= 1;
	    ymove >>= 1;
	}
	else
	{
	    ptryx = mo->x + xmove;
	    ptryy = mo->y + ymove;
	    xmove = ymove = 0;
	}
		
	if (!P_TryMove (mo, ptryx, ptryy))
	{
	    // blocked move
	    if (mo->player)
	    {	// try to slide along it
		P_SlideMove (mo);
	    }
	    else if (mo->flags & MF_MISSILE)
	    {
		// explode a missile
		if (ceilingline &&
		    ceilingline->backsector &&
		    ceilingline->backsector->ceilingpic == skyflatnum)
		{
		    // Hack to prevent missiles exploding
		    // against the sky.
		    // Does not handle sky floors.
		    P_RemoveMobj (mo);
		    return;
		}
		P_ExplodeMissile (mo);
	    }
	    else
		mo->momx = mo->momy = 0;
	}
    } while (xmove || ymove);
    
    // slow down
    if (player && player->cheats & CF_NOMOMENTUM)
    {
	// debug option for no sliding at all
	mo->momx = mo->momy = 0;
	return;
    }

    if (mo->flags & (MF_MISSILE | MF_SKULLFLY) )
	return; 	// no friction for missiles ever
		
    if (mo->z > mo->floorz)
	return;		// no friction when airborne

    if (mo->flags & MF_CORPSE)
    {
	// do not stop sliding
	//  if halfway off a step with some momentum
	if (mo->momx > FRACUNIT/4
	    || mo->momx < -FRACUNIT/4
	    || mo->momy > FRACUNIT/4
	    || mo->momy < -FRACUNIT/4)
	{
	    if (mo->floorz != mo->subsector->sector->floorheight)
		return;
	}
    }

    if (mo->momx > -STOPSPEED
	&& mo->momx < STOPSPEED
	&& mo->momy > -STOPSPEED
	&& mo->momy < STOPSPEED
	&& (!player
	    || (player->cmd.forwardmove== 0
		&& player->cmd.sidemove == 0 ) ) )
    {
	// if in a walking frame, stop moving
	if ( player&&(unsigned)((player->mo->state - states)- S_PLAY_RUN1) < 4)
	    P_SetMobjState (player->mo, S_PLAY);
	
	mo->momx = 0;
	mo->momy = 0;
    }
    else
    {
	mo->momx = FixedMul (mo->momx, FRICTION);
	mo->momy = FixedMul (mo->momy, FRICTION);
    }
}

//
// P_ZMovement
//
void P_ZMovement (mobj_t* mo)
{
    fixed_t	dist;
    fixed_t	delta;
    
    // check for smooth step up
    if (mo->player && mo->z < mo->floorz)
    {
	mo->player->viewheight -= mo->floorz-mo->z;

	mo->player->deltaviewheight
	    = (VIEWHEIGHT - mo->player->viewheight)>>3;
    }
    
    // adjust height
    mo->z += mo->momz;
	
    if ( mo->flags & MF_FLOAT
	 && mo->target)
    {
	// float down towards target if too close
	if ( !(mo->flags & MF_SKULLFLY)
	     && !(mo->flags & MF_INFLOAT) )
	{
	    dist = P_AproxDistance (mo->x - mo->target->x,
				    mo->y - mo->target->y);
	    
	    delta =(mo->target->z + (mo->height>>1)) - mo->z;

	    if (delta<0 && dist < -(delta*3) )
		mo->z -= FLOATSPEED;
	    else if (delta>0 && dist < (delta*3) )
		mo->z += FLOATSPEED;			
	}
	
    }
    
    // clip movement
    if (mo->z <= mo->floorz)
    {
	// hit the floor

	// Note (id):
	//  somebody left this after the setting momz to 0,
	//  kinda useless there.
	if (mo->flags & MF_SKULLFLY)
	{
	    // the skull slammed into something
	    mo->momz = -mo->momz;
	}
	
	if (mo->momz < 0)
	{
	    if (mo->player
		&& mo->momz < -GRAVITY*8)	
	    {
		// Squat down.
		// Decrease viewheight for a moment
		// after hitting the ground (hard),
		// and utter appropriate sound.
		mo->player->deltaviewheight = mo->momz>>3;
		S_StartSound (mo, sfx_oof);
	    }
	    mo->momz = 0;
	}
	mo->z = mo->floorz;

	if ( (mo->flags & MF_MISSILE)
	     && !(mo->flags & MF_NOCLIP) )
	{
	    P_ExplodeMissile (mo);
	    return;
	}
    }
    else if (! (mo->flags & MF_NOGRAVITY) )
    {
	if (mo->momz == 0)
	    mo->momz = -GRAVITY*2;
	else
	    mo->momz -= GRAVITY;
    }
	
    if (mo->z + mo->height > mo->ceilingz)
    {
	// hit the ceiling
	if (mo->momz > 0)
	    mo->momz = 0;
	{
	    mo->z = mo->ceilingz - mo->height;
	}

	if (mo->flags & MF_SKULLFLY)
	{	// the skull slammed into something
	    mo->momz = -mo->momz;
	}
	
	if ( (mo->flags & MF_MISSILE)
	     && !(mo->flags & MF_NOCLIP) )
	{
	    P_ExplodeMissile (mo);
	    return;
	}
    }
} 



//
// P_NightmareRespawn
//
void
P_NightmareRespawn (mobj_t* mobj)
{
    fixed_t		x;
    fixed_t		y;
    fixed_t		z; 
    subsector_t*	ss; 
    mobj_t*		mo;
    mapthing_t*		mthing;
		
    x = mobj->spawnpoint.x << FRACBITS; 
    y = mobj->spawnpoint.y << FRACBITS; 

    // somthing is occupying it's position?
    if (!P_CheckPosition (mobj, x, y) ) 
	return;	// no respwan

    // spawn a teleport fog at old spot
    // because of removal of the body?
    mo = P_SpawnMobj (mobj->x,
		      mobj->y,
		      mobj->subsector->sector->floorheight , MT_TFOG); 
    // initiate teleport sound
    S_StartSound (mo, sfx_telept);

    // spawn a teleport fog at the new spot
    ss = R_PointInSubsector (x,y); 

    mo = P_SpawnMobj (x, y, ss->sector->floorheight , MT_TFOG); 

    S_StartSound (mo, sfx_telept);

    // spawn the new monster
    mthing = &mobj->spawnpoint;
	
    // spawn it
    if (mobj->info->flags & MF_SPAWNCEILING)
	z = ONCEILINGZ;
    else
	z = ONFLOORZ;

    // inherit attributes from deceased one
    mo = P_SpawnMobj (x,y,z, mobj->type);
    mo->spawnpoint = mobj->spawnpoint;	
    mo->angle = ANG45 * (mthing->angle/45);

    if (mthing->options & MTF_AMBUSH)
	mo->flags |= MF_AMBUSH;

    mo->reactiontime = 18;
	
    // remove the old monster,
    P_RemoveMobj (mobj);
}


//
// P_MobjThinker
//
void P_MobjThinker (mobj_t* mobj)
{

    // momentum movement
    if (mobj->momx
	|| mobj->momy
	|| (mobj->flags&MF_SKULLFLY) )
    {
	    P_XYMovement (mobj);


	    // FIXME: decent NOP/NULL/Nil function pointer please.
	    if (mobj->thinker.function.acv == (actionf_v) (-1))
	        return;		// mobj was removed
    }
    if ( (mobj->z != mobj->floorz)
	 || mobj->momz )
    {
	    P_ZMovement (mobj);
	
	// FIXME: decent NOP/NULL/Nil function pointer please.
	if (mobj->thinker.function.acv == (actionf_v) (-1))
	    return;		// mobj was removed
    }

   
    // cycle through states,
    // calling action functions at transitions
    if (mobj->tics != -1)
    {
	    mobj->tics--;
		    
	    // you can cycle through multiple states in a tic
	    if (!mobj->tics)
	        if (!P_SetMobjState (mobj, mobj->state->nextstate) )
		    return;		// freed itself
    }
    else
    {
	// check for nightmare respawn
	if (! (mobj->flags & MF_COUNTKILL) )
	    return;

	if (!respawnmonsters)
	    return;

	mobj->movecount++;

	if (mobj->movecount < 12*35)
	    return;

	if ( leveltime&31 )
	    return;

	if (P_Random () > 4)
	    return;

	P_NightmareRespawn (mobj);
    }

}


//
// P_SpawnMobj
//
mobj_t*
P_SpawnMobj
( fixed_t	x,
  fixed_t	y,
  fixed_t	z,
  mobjtype_t	type )
{
    mobj_t*	mobj;
    state_t*	st;
    mobjinfo_t*	info;
	
    mobj = Z_Malloc (sizeof(*mobj), PU_LEVEL, NULL);
    memset (mobj, 0, sizeof (*mobj));
    info = &mobjinfo[type];
	
    mobj->type = type;
    mobj->info = info;
    mobj->x = x;
    mobj->y = y;
    mobj->radius = info->radius;
    mobj->height = info->height;
    mobj->flags = info->flags;
    mobj->health = info->spawnhealth;

    if (gameskill != sk_nightmare)
	mobj->reactiontime = info->reactiontime;
    
    mobj->lastlook = P_Random () % MAXPLAYERS;
    // do not set the state with P_SetMobjState,
    // because action routines can not be called yet
    st = &states[info->spawnstate];

    mobj->state = st;
    mobj->tics = st->tics;
    mobj->sprite = st->sprite;
    mobj->frame = st->frame;

    // set subsector and/or block links
    P_SetThingPosition (mobj);
	
    mobj->floorz = mobj->subsector->sector->floorheight;
    mobj->ceilingz = mobj->subsector->sector->ceilingheight;

    if (z == ONFLOORZ)
	mobj->z = mobj->floorz;
    else if (z == ONCEILINGZ)
	mobj->z = mobj->ceilingz - mobj->info->height;
    else 
	mobj->z = z;

    mobj->thinker.function.acp1 = (actionf_p1)P_MobjThinker;
	
    P_AddThinker (&mobj->thinker);

    return mobj;
}


//
// P_RemoveMobj
//
mapthing_t	itemrespawnque[ITEMQUESIZE];
int		itemrespawntime[ITEMQUESIZE];
int		iquehead;
int		iquetail;


void P_RemoveMobj (mobj_t* mobj)
{
    if ((mobj->flags & MF_SPECIAL)
	&& !(mobj->flags & MF_DROPPED)
	&& (mobj->type != MT_INV)
	&& (mobj->type != MT_INS))
    {
	itemrespawnque[iquehead] = mobj->spawnpoint;
	itemrespawntime[iquehead] = leveltime;
	iquehead = (iquehead+1)&(ITEMQUESIZE-1);

	// lose one off the end?
	if (iquehead == iquetail)
	    iquetail = (iquetail+1)&(ITEMQUESIZE-1);
    }
	
    // unlink from sector and block lists
    P_UnsetThingPosition (mobj);
    
    // stop any playing sound
    S_StopSound (mobj);
    
    // free block
    P_RemoveThinker ((thinker_t*)mobj);
}




//
// P_RespawnSpecials
//
void P_RespawnSpecials (void)
{
    fixed_t		x;
    fixed_t		y;
    fixed_t		z;
    
    subsector_t*	ss; 
    mobj_t*		mo;
    mapthing_t*		mthing;
    
    int			i;

    // only respawn items in deathmatch
    if (deathmatch != 2)
	return;	// 

    // nothing left to respawn?
    if (iquehead == iquetail)
	return;		

    // wait at least 30 seconds
    if (leveltime - itemrespawntime[iquetail] < 30*35)
	return;			

    mthing = &itemrespawnque[iquetail];
	
    x = mthing->x << FRACBITS; 
    y = mthing->y << FRACBITS; 
	  
    // spawn a teleport fog at the new spot
    ss = R_PointInSubsector (x,y); 
    mo = P_SpawnMobj (x, y, ss->sector->floorheight , MT_IFOG); 
    S_StartSound (mo, sfx_itmbk);

    // find which type to spawn
    for (i=0 ; i< NUMMOBJTYPES ; i++)
    {
	if (mthing->type == mobjinfo[i].doomednum)
	    break;
    }
    
    // spawn it
    if (mobjinfo[i].flags & MF_SPAWNCEILING)
	z = ONCEILINGZ;
    else
	z = ONFLOORZ;

    mo = P_SpawnMobj (x,y,z, i);
    mo->spawnpoint = *mthing;	
    mo->angle = ANG45 * (mthing->angle/45);

    // pull it from the que
    iquetail = (iquetail+1)&(ITEMQUESIZE-1);
}




//
// P_SpawnPlayer
// Called when a player is spawned on the level.
// Most of the player structure stays unchanged
//  between levels.
//
void P_SpawnPlayer (mapthing_t* mthing)
{
    player_t*		p;
    fixed_t		x;
    fixed_t		y;
    fixed_t		z;

    mobj_t*		mobj;

    int			i;

    // not playing?
    if (!playeringame[mthing->type-1])
	return;					
		
    p = &players[mthing->type-1];

    if (p->playerstate == PST_REBORN)
	G_PlayerReborn (mthing->type-1);

    x 		= mthing->x << FRACBITS;
    y 		= mthing->y << FRACBITS;
    z		= ONFLOORZ;
    mobj	= P_SpawnMobj (x,y,z, MT_PLAYER);

    // set color translations for player sprites
    if (mthing->type > 1)		
	mobj->flags |= (mthing->type-1)<<MF_TRANSSHIFT;
		
    mobj->angle	= ANG45 * (mthing->angle/45);
    mobj->player = p;
    mobj->health = p->health;

    p->mo = mobj;
    p->playerstate = PST_LIVE;	
    p->refire = 0;
    p->message = NULL;
    p->damagecount = 0;
    p->bonuscount = 0;
    p->extralight = 0;
    p->fixedcolormap = 0;
    p->viewheight = VIEWHEIGHT;

    // setup gun psprite
    P_SetupPsprites (p);
    
    // give all cards in death match mode
    if (deathmatch)
	for (i=0 ; i<NUMCARDS ; i++)
	    p->cards[i] = true;
			
    if (mthing->type-1 == consoleplayer)
    {
	// wake up the status bar
	ST_Start ();
	// wake up the heads up text
	HU_Start ();		
    }
}


//
// P_SpawnMapThing
// The fields of the mapthing should
// already be in host byte order.
//
void P_SpawnMapThing (mapthing_t* mthing)
{
    int			i;
    int			bit;
    mobj_t*		mobj;
    fixed_t		x;
    fixed_t		y;
    fixed_t		z;
		
    // count deathmatch start positions
    if (mthing->type == 11)
    {
	if (deathmatch_p < &deathmatchstarts[10])
	{
	    memcpy (deathmatch_p, mthing, sizeof(*mthing));
	    deathmatch_p++;
	}
	return;
    }
	
    // check for players specially
    if (mthing->type <= 4)
    {
	// save spots for respawning in network games
	playerstarts[mthing->type-1] = *mthing;
	if (!deathmatch)
	    P_SpawnPlayer (mthing);

	return;
    }

    // check for apropriate skill level
    if (!netgame && (mthing->options & 16) )
	return;
		
    if (gameskill == sk_baby)
	bit = 1;
    else if (gameskill == sk_nightmare)
	bit = 4;
    else
	bit = 1<<(gameskill-1);

    if (!(mthing->options & bit) )
	return;
	
    // find which type to spawn
    for (i=0 ; i< NUMMOBJTYPES ; i++)
	if (mthing->type == mobjinfo[i].doomednum)
	    break;
	
    if (i==NUMMOBJTYPES)
	I_Error ("P_SpawnMapThing: Unknown type %i at (%i, %i)",
		 mthing->type,
		 mthing->x, mthing->y);
		
    // don't spawn keycards and players in deathmatch
    if (deathmatch && mobjinfo[i].flags & MF_NOTDMATCH)
	return;
		
    // don't spawn any monsters if -nomonsters
    if (nomonsters
	&& ( i == MT_SKULL
	     || (mobjinfo[i].flags & MF_COUNTKILL)) )
    {
	return;
    }
    
    // spawn it
    x = mthing->x << FRACBITS;
    y = mthing->y << FRACBITS;

    if (mobjinfo[i].flags & MF_SPAWNCEILING)
	z = ONCEILINGZ;
    else
	z = ONFLOORZ;
    
    mobj = P_SpawnMobj (x,y,z, i);
    mobj->spawnpoint = *mthing;

    if (mobj->tics > 0)
	mobj->tics = 1 + (P_Random () % mobj->tics);
    if (mobj->flags & MF_COUNTKILL)
	totalkills++;
    if (mobj->flags & MF_COUNTITEM)
		totalitems++;
		
    mobj->angle = ANG45 * (mthing->angle/45);
    if (mthing->options & MTF_AMBUSH)
	mobj->flags |= MF_AMBUSH;
}



//
// GAME SPAWN FUNCTIONS
//


//
// P_SpawnPuff
//
extern fixed_t attackrange;

void
P_SpawnPuff
( fixed_t	x,
  fixed_t	y,
  fixed_t	z )
{
    mobj_t*	th;
	
    z += ((P_Random()-P_Random())<<10);

    th = P_SpawnMobj (x,y,z, MT_PUFF);
    th->momz = FRACUNIT;
    th->tics -= P_Random()&3;

    if (th->tics < 1)
	th->tics = 1;
	
    // don't make punches spark on the wall
    if (attackrange == MELEERANGE)
	P_SetMobjState (th, S_PUFF3);
}



//
// P_SpawnBlood
// 
void
P_SpawnBlood
( fixed_t	x,
  fixed_t	y,
  fixed_t	z,
  int		damage )
{
    mobj_t*	th;
	
    z += ((P_Random()-P_Random())<<10);
    th = P_SpawnMobj (x,y,z, MT_BLOOD);
    th->momz = FRACUNIT*2;
    th->tics -= P_Random()&3;

    if (th->tics < 1)
	th->tics = 1;
		
    if (damage <= 12 && damage >= 9)
	P_SetMobjState (th,S_BLOOD2);
    else if (damage < 9)
	P_SetMobjState (th,S_BLOOD3);
}



//
// P_CheckMissileSpawn
// Moves the missile forward a bit
//  and possibly explodes it right there.
//
void P_CheckMissileSpawn (mobj_t* th)
{
    th->tics -= P_Random()&3;
    if (th->tics < 1)
	th->tics = 1;
    
    // move a little forward so an angle can
    // be computed if it immediately explodes
    th->x += (th->momx>>1);
    th->y += (th->momy>>1);
    th->z += (th->momz>>1);

    if (!P_TryMove (th, th->x, th->y))
	P_ExplodeMissile (th);
}


//
// P_SpawnMissile
//
mobj_t*
P_SpawnMissile
( mobj_t*	source,
  mobj_t*	dest,
  mobjtype_t	type )
{
    mobj_t*	th;
    angle_t	an;
    int		dist;

    th = P_SpawnMobj (source->x,
		      source->y,
		      source->z + 4*8*FRACUNIT, type);
    
    if (th->info->seesound)
	S_StartSound (th, th->info->seesound);

    th->target = source;	// where it came from
    an = R_PointToAngle2 (source->x, source->y, dest->x, dest->y);	

    // fuzzy player
    if (dest->flags & MF_SHADOW)
	an += (P_Random()-P_Random())<<20;	

    th->angle = an;
    an >>= ANGLETOFINESHIFT;
    th->momx = FixedMul (th->info->speed, _finecosine(an));
    th->momy = FixedMul (th->info->speed, _finesine(an));
	
    dist = P_AproxDistance (dest->x - source->x, dest->y - source->y);
    dist = dist / th->info->speed;

    if (dist < 1)
	dist = 1;

    th->momz = (dest->z - source->z) / dist;
    P_CheckMissileSpawn (th);
	
    return th;
}


//
// P_SpawnPlayerMissile
// Tries to aim at a nearby monster
//
void
P_SpawnPlayerMissile
( mobj_t*	source,
  mobjtype_t	type )
{
    mobj_t*	th;
    angle_t	an;
    
    fixed_t	x;
    fixed_t	y;
    fixed_t	z;
    fixed_t	slope;
    
    // see which target is to be aimed at
    an = source->angle;
    slope = P_AimLineAttack (source, an, 16*64*FRACUNIT);
    
    if (!linetarget)
    {
	an += 1<<26;
	slope = P_AimLineAttack (source, an, 16*64*FRACUNIT);

	if (!linetarget)
	{
	    an -= 2<<26;
	    slope = P_AimLineAttack (source, an, 16*64*FRACUNIT);
	}

	if (!linetarget)
	{
	    an = source->angle;
	    slope = 0;
	}
    }
		
    x = source->x;
    y = source->y;
    z = source->z + 4*8*FRACUNIT;
	
    th = P_SpawnMobj (x,y,z, type);

    if (th->info->seesound)
	S_StartSound (th, th->info->seesound);

    th->target = source;
    th->angle = an;
    th->momx = FixedMul( th->info->speed,
			 _finecosine(an>>ANGLETOFINESHIFT));
    th->momy = FixedMul( th->info->speed,
			 _finesine(an>>ANGLETOFINESHIFT));
    th->momz = FixedMul( th->info->speed, slope);

    P_CheckMissileSpawn (th);
}

