//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WinDoom.rc
//
#define IDR_ACCELERATOR1                105
#define ACC01                           40001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
